package org.ffmpeg.avformat57;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavformat\avio.h:52</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVIODirContext extends Structure {
	/** C type : void* */
	public Pointer url_context;
	public AVIODirContext() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("url_context");
	}
	/** @param url_context C type : void* */
	public AVIODirContext(Pointer url_context) {
		super();
		this.url_context = url_context;
	}
	public static class ByReference extends AVIODirContext implements Structure.ByReference {
		
	};
	public static class ByValue extends AVIODirContext implements Structure.ByValue {
		
	};
}
