package org.ffmpeg.avutil55;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavutil\pixdesc.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVComponentDescriptor extends Structure {
	public int plane;
	public int step;
	public int offset;
	public int shift;
	public int depth;
	public int step_minus1;
	public int depth_minus1;
	public int offset_plus1;
	public AVComponentDescriptor() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("plane", "step", "offset", "shift", "depth", "step_minus1", "depth_minus1", "offset_plus1");
	}
	public AVComponentDescriptor(int plane, int step, int offset, int shift, int depth, int step_minus1, int depth_minus1, int offset_plus1) {
		super();
		this.plane = plane;
		this.step = step;
		this.offset = offset;
		this.shift = shift;
		this.depth = depth;
		this.step_minus1 = step_minus1;
		this.depth_minus1 = depth_minus1;
		this.offset_plus1 = offset_plus1;
	}
	public AVComponentDescriptor(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVComponentDescriptor implements Structure.ByReference {
		
	};
	public static class ByValue extends AVComponentDescriptor implements Structure.ByValue {
		
	};
}
