package org.ffmpeg.avcodec;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.ffmpeg.avcodec.AVCodecLibrary.AVAudioServiceType;
import org.ffmpeg.avcodec.AVCodecLibrary.AVCodecID;
import org.ffmpeg.avcodec.AVCodecLibrary.AVDiscard;
import org.ffmpeg.avcodec.AVCodecLibrary.AVFieldOrder;
import org.ffmpeg.avutil.AVBufferRef;
import org.ffmpeg.avutil.AVClass;
import org.ffmpeg.avutil.AVFrame;
import org.ffmpeg.avutil.AVRational;
import org.ffmpeg.avutil.AVUtilLibrary.AVChromaLocation;
import org.ffmpeg.avutil.AVUtilLibrary.AVColorPrimaries;
import org.ffmpeg.avutil.AVUtilLibrary.AVColorRange;
import org.ffmpeg.avutil.AVUtilLibrary.AVColorSpace;
import org.ffmpeg.avutil.AVUtilLibrary.AVColorTransferCharacteristic;
import org.ffmpeg.avutil.AVUtilLibrary.AVMediaType;
import org.ffmpeg.avutil.AVUtilLibrary.AVPixelFormat;
import org.ffmpeg.avutil.AVUtilLibrary.AVSampleFormat;
/**
 * <i>native declaration : .\libavcodec\avcodec.h:937</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avcodec-57") 
public class AVCodecContext extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : const AVClass* */
	@Field(0) 
	public Pointer<AVClass > av_class() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : const AVClass* */
	@Field(0) 
	public AVCodecContext av_class(Pointer<AVClass > av_class) {
		this.io.setPointerField(this, 0, av_class);
		return this;
	}
	@Field(1) 
	public int log_level_offset() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public AVCodecContext log_level_offset(int log_level_offset) {
		this.io.setIntField(this, 1, log_level_offset);
		return this;
	}
	/**
	 * see AVMEDIA_TYPE_xxx<br>
	 * C type : AVMediaType
	 */
	@Field(2) 
	public IntValuedEnum<AVMediaType > codec_type() {
		return this.io.getEnumField(this, 2);
	}
	/**
	 * see AVMEDIA_TYPE_xxx<br>
	 * C type : AVMediaType
	 */
	@Field(2) 
	public AVCodecContext codec_type(IntValuedEnum<AVMediaType > codec_type) {
		this.io.setEnumField(this, 2, codec_type);
		return this;
	}
	/** C type : AVCodec* */
	@Field(3) 
	public Pointer<AVCodec > codec() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : AVCodec* */
	@Field(3) 
	public AVCodecContext codec(Pointer<AVCodec > codec) {
		this.io.setPointerField(this, 3, codec);
		return this;
	}
	/** C type : char[32] */
	@Array({32}) 
	@Field(4) 
	public Pointer<Byte > codec_name() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * see AV_CODEC_ID_xxx<br>
	 * C type : AVCodecID
	 */
	@Field(5) 
	public IntValuedEnum<AVCodecID > codec_id() {
		return this.io.getEnumField(this, 5);
	}
	/**
	 * see AV_CODEC_ID_xxx<br>
	 * C type : AVCodecID
	 */
	@Field(5) 
	public AVCodecContext codec_id(IntValuedEnum<AVCodecID > codec_id) {
		this.io.setEnumField(this, 5, codec_id);
		return this;
	}
	@Field(6) 
	public int codec_tag() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public AVCodecContext codec_tag(int codec_tag) {
		this.io.setIntField(this, 6, codec_tag);
		return this;
	}
	@Field(7) 
	public int stream_codec_tag() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public AVCodecContext stream_codec_tag(int stream_codec_tag) {
		this.io.setIntField(this, 7, stream_codec_tag);
		return this;
	}
	/** C type : void* */
	@Field(8) 
	public Pointer<? > priv_data() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : void* */
	@Field(8) 
	public AVCodecContext priv_data(Pointer<? > priv_data) {
		this.io.setPointerField(this, 8, priv_data);
		return this;
	}
	/** C type : AVCodecInternal* */
	@Field(9) 
	public Pointer<AVCodecInternal > internal() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : AVCodecInternal* */
	@Field(9) 
	public AVCodecContext internal(Pointer<AVCodecInternal > internal) {
		this.io.setPointerField(this, 9, internal);
		return this;
	}
	/** C type : void* */
	@Field(10) 
	public Pointer<? > opaque() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : void* */
	@Field(10) 
	public AVCodecContext opaque(Pointer<? > opaque) {
		this.io.setPointerField(this, 10, opaque);
		return this;
	}
	@Field(11) 
	public long bit_rate() {
		return this.io.getLongField(this, 11);
	}
	@Field(11) 
	public AVCodecContext bit_rate(long bit_rate) {
		this.io.setLongField(this, 11, bit_rate);
		return this;
	}
	@Field(12) 
	public int bit_rate_tolerance() {
		return this.io.getIntField(this, 12);
	}
	@Field(12) 
	public AVCodecContext bit_rate_tolerance(int bit_rate_tolerance) {
		this.io.setIntField(this, 12, bit_rate_tolerance);
		return this;
	}
	@Field(13) 
	public int global_quality() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public AVCodecContext global_quality(int global_quality) {
		this.io.setIntField(this, 13, global_quality);
		return this;
	}
	@Field(14) 
	public int compression_level() {
		return this.io.getIntField(this, 14);
	}
	@Field(14) 
	public AVCodecContext compression_level(int compression_level) {
		this.io.setIntField(this, 14, compression_level);
		return this;
	}
	@Field(15) 
	public int flags() {
		return this.io.getIntField(this, 15);
	}
	@Field(15) 
	public AVCodecContext flags(int flags) {
		this.io.setIntField(this, 15, flags);
		return this;
	}
	@Field(16) 
	public int flags2() {
		return this.io.getIntField(this, 16);
	}
	@Field(16) 
	public AVCodecContext flags2(int flags2) {
		this.io.setIntField(this, 16, flags2);
		return this;
	}
	/** C type : uint8_t* */
	@Field(17) 
	public Pointer<Byte > extradata() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : uint8_t* */
	@Field(17) 
	public AVCodecContext extradata(Pointer<Byte > extradata) {
		this.io.setPointerField(this, 17, extradata);
		return this;
	}
	@Field(18) 
	public int extradata_size() {
		return this.io.getIntField(this, 18);
	}
	@Field(18) 
	public AVCodecContext extradata_size(int extradata_size) {
		this.io.setIntField(this, 18, extradata_size);
		return this;
	}
	/** C type : AVRational */
	@Field(19) 
	public AVRational time_base() {
		return this.io.getNativeObjectField(this, 19);
	}
	/** C type : AVRational */
	@Field(19) 
	public AVCodecContext time_base(AVRational time_base) {
		this.io.setNativeObjectField(this, 19, time_base);
		return this;
	}
	@Field(20) 
	public int ticks_per_frame() {
		return this.io.getIntField(this, 20);
	}
	@Field(20) 
	public AVCodecContext ticks_per_frame(int ticks_per_frame) {
		this.io.setIntField(this, 20, ticks_per_frame);
		return this;
	}
	@Field(21) 
	public int delay() {
		return this.io.getIntField(this, 21);
	}
	@Field(21) 
	public AVCodecContext delay(int delay) {
		this.io.setIntField(this, 21, delay);
		return this;
	}
	@Field(22) 
	public int width() {
		return this.io.getIntField(this, 22);
	}
	@Field(22) 
	public AVCodecContext width(int width) {
		this.io.setIntField(this, 22, width);
		return this;
	}
	@Field(23) 
	public int height() {
		return this.io.getIntField(this, 23);
	}
	@Field(23) 
	public AVCodecContext height(int height) {
		this.io.setIntField(this, 23, height);
		return this;
	}
	@Field(24) 
	public int coded_width() {
		return this.io.getIntField(this, 24);
	}
	@Field(24) 
	public AVCodecContext coded_width(int coded_width) {
		this.io.setIntField(this, 24, coded_width);
		return this;
	}
	@Field(25) 
	public int coded_height() {
		return this.io.getIntField(this, 25);
	}
	@Field(25) 
	public AVCodecContext coded_height(int coded_height) {
		this.io.setIntField(this, 25, coded_height);
		return this;
	}
	@Field(26) 
	public int gop_size() {
		return this.io.getIntField(this, 26);
	}
	@Field(26) 
	public AVCodecContext gop_size(int gop_size) {
		this.io.setIntField(this, 26, gop_size);
		return this;
	}
	/** C type : AVPixelFormat */
	@Field(27) 
	public IntValuedEnum<AVPixelFormat > pix_fmt() {
		return this.io.getEnumField(this, 27);
	}
	/** C type : AVPixelFormat */
	@Field(27) 
	public AVCodecContext pix_fmt(IntValuedEnum<AVPixelFormat > pix_fmt) {
		this.io.setEnumField(this, 27, pix_fmt);
		return this;
	}
	@Field(28) 
	public int me_method() {
		return this.io.getIntField(this, 28);
	}
	@Field(28) 
	public AVCodecContext me_method(int me_method) {
		this.io.setIntField(this, 28, me_method);
		return this;
	}
	/** C type : draw_horiz_band_callback* */
	@Field(29) 
	public Pointer<draw_horiz_band_callback > draw_horiz_band() {
		return this.io.getPointerField(this, 29);
	}
	/** C type : draw_horiz_band_callback* */
	@Field(29) 
	public AVCodecContext draw_horiz_band(Pointer<draw_horiz_band_callback > draw_horiz_band) {
		this.io.setPointerField(this, 29, draw_horiz_band);
		return this;
	}
	@CLong 
	@Field(30) 
	public long get_format() {
		return this.io.getCLongField(this, 30);
	}
	@CLong 
	@Field(30) 
	public AVCodecContext get_format(long get_format) {
		this.io.setCLongField(this, 30, get_format);
		return this;
	}
	@Field(31) 
	public int max_b_frames() {
		return this.io.getIntField(this, 31);
	}
	@Field(31) 
	public AVCodecContext max_b_frames(int max_b_frames) {
		this.io.setIntField(this, 31, max_b_frames);
		return this;
	}
	@Field(32) 
	public float b_quant_factor() {
		return this.io.getFloatField(this, 32);
	}
	@Field(32) 
	public AVCodecContext b_quant_factor(float b_quant_factor) {
		this.io.setFloatField(this, 32, b_quant_factor);
		return this;
	}
	@Field(33) 
	public int rc_strategy() {
		return this.io.getIntField(this, 33);
	}
	@Field(33) 
	public AVCodecContext rc_strategy(int rc_strategy) {
		this.io.setIntField(this, 33, rc_strategy);
		return this;
	}
	@Field(34) 
	public int b_frame_strategy() {
		return this.io.getIntField(this, 34);
	}
	@Field(34) 
	public AVCodecContext b_frame_strategy(int b_frame_strategy) {
		this.io.setIntField(this, 34, b_frame_strategy);
		return this;
	}
	@Field(35) 
	public float b_quant_offset() {
		return this.io.getFloatField(this, 35);
	}
	@Field(35) 
	public AVCodecContext b_quant_offset(float b_quant_offset) {
		this.io.setFloatField(this, 35, b_quant_offset);
		return this;
	}
	@Field(36) 
	public int has_b_frames() {
		return this.io.getIntField(this, 36);
	}
	@Field(36) 
	public AVCodecContext has_b_frames(int has_b_frames) {
		this.io.setIntField(this, 36, has_b_frames);
		return this;
	}
	@Field(37) 
	public int mpeg_quant() {
		return this.io.getIntField(this, 37);
	}
	@Field(37) 
	public AVCodecContext mpeg_quant(int mpeg_quant) {
		this.io.setIntField(this, 37, mpeg_quant);
		return this;
	}
	@Field(38) 
	public float i_quant_factor() {
		return this.io.getFloatField(this, 38);
	}
	@Field(38) 
	public AVCodecContext i_quant_factor(float i_quant_factor) {
		this.io.setFloatField(this, 38, i_quant_factor);
		return this;
	}
	@Field(39) 
	public float i_quant_offset() {
		return this.io.getFloatField(this, 39);
	}
	@Field(39) 
	public AVCodecContext i_quant_offset(float i_quant_offset) {
		this.io.setFloatField(this, 39, i_quant_offset);
		return this;
	}
	@Field(40) 
	public float lumi_masking() {
		return this.io.getFloatField(this, 40);
	}
	@Field(40) 
	public AVCodecContext lumi_masking(float lumi_masking) {
		this.io.setFloatField(this, 40, lumi_masking);
		return this;
	}
	@Field(41) 
	public float temporal_cplx_masking() {
		return this.io.getFloatField(this, 41);
	}
	@Field(41) 
	public AVCodecContext temporal_cplx_masking(float temporal_cplx_masking) {
		this.io.setFloatField(this, 41, temporal_cplx_masking);
		return this;
	}
	@Field(42) 
	public float spatial_cplx_masking() {
		return this.io.getFloatField(this, 42);
	}
	@Field(42) 
	public AVCodecContext spatial_cplx_masking(float spatial_cplx_masking) {
		this.io.setFloatField(this, 42, spatial_cplx_masking);
		return this;
	}
	@Field(43) 
	public float p_masking() {
		return this.io.getFloatField(this, 43);
	}
	@Field(43) 
	public AVCodecContext p_masking(float p_masking) {
		this.io.setFloatField(this, 43, p_masking);
		return this;
	}
	@Field(44) 
	public float dark_masking() {
		return this.io.getFloatField(this, 44);
	}
	@Field(44) 
	public AVCodecContext dark_masking(float dark_masking) {
		this.io.setFloatField(this, 44, dark_masking);
		return this;
	}
	@Field(45) 
	public int slice_count() {
		return this.io.getIntField(this, 45);
	}
	@Field(45) 
	public AVCodecContext slice_count(int slice_count) {
		this.io.setIntField(this, 45, slice_count);
		return this;
	}
	@Field(46) 
	public int prediction_method() {
		return this.io.getIntField(this, 46);
	}
	@Field(46) 
	public AVCodecContext prediction_method(int prediction_method) {
		this.io.setIntField(this, 46, prediction_method);
		return this;
	}
	/** C type : int* */
	@Field(47) 
	public Pointer<Integer > slice_offset() {
		return this.io.getPointerField(this, 47);
	}
	/** C type : int* */
	@Field(47) 
	public AVCodecContext slice_offset(Pointer<Integer > slice_offset) {
		this.io.setPointerField(this, 47, slice_offset);
		return this;
	}
	/** C type : AVRational */
	@Field(48) 
	public AVRational sample_aspect_ratio() {
		return this.io.getNativeObjectField(this, 48);
	}
	/** C type : AVRational */
	@Field(48) 
	public AVCodecContext sample_aspect_ratio(AVRational sample_aspect_ratio) {
		this.io.setNativeObjectField(this, 48, sample_aspect_ratio);
		return this;
	}
	@Field(49) 
	public int me_cmp() {
		return this.io.getIntField(this, 49);
	}
	@Field(49) 
	public AVCodecContext me_cmp(int me_cmp) {
		this.io.setIntField(this, 49, me_cmp);
		return this;
	}
	@Field(50) 
	public int me_sub_cmp() {
		return this.io.getIntField(this, 50);
	}
	@Field(50) 
	public AVCodecContext me_sub_cmp(int me_sub_cmp) {
		this.io.setIntField(this, 50, me_sub_cmp);
		return this;
	}
	@Field(51) 
	public int mb_cmp() {
		return this.io.getIntField(this, 51);
	}
	@Field(51) 
	public AVCodecContext mb_cmp(int mb_cmp) {
		this.io.setIntField(this, 51, mb_cmp);
		return this;
	}
	@Field(52) 
	public int ildct_cmp() {
		return this.io.getIntField(this, 52);
	}
	@Field(52) 
	public AVCodecContext ildct_cmp(int ildct_cmp) {
		this.io.setIntField(this, 52, ildct_cmp);
		return this;
	}
	@Field(53) 
	public int dia_size() {
		return this.io.getIntField(this, 53);
	}
	@Field(53) 
	public AVCodecContext dia_size(int dia_size) {
		this.io.setIntField(this, 53, dia_size);
		return this;
	}
	@Field(54) 
	public int last_predictor_count() {
		return this.io.getIntField(this, 54);
	}
	@Field(54) 
	public AVCodecContext last_predictor_count(int last_predictor_count) {
		this.io.setIntField(this, 54, last_predictor_count);
		return this;
	}
	@Field(55) 
	public int pre_me() {
		return this.io.getIntField(this, 55);
	}
	@Field(55) 
	public AVCodecContext pre_me(int pre_me) {
		this.io.setIntField(this, 55, pre_me);
		return this;
	}
	@Field(56) 
	public int me_pre_cmp() {
		return this.io.getIntField(this, 56);
	}
	@Field(56) 
	public AVCodecContext me_pre_cmp(int me_pre_cmp) {
		this.io.setIntField(this, 56, me_pre_cmp);
		return this;
	}
	@Field(57) 
	public int pre_dia_size() {
		return this.io.getIntField(this, 57);
	}
	@Field(57) 
	public AVCodecContext pre_dia_size(int pre_dia_size) {
		this.io.setIntField(this, 57, pre_dia_size);
		return this;
	}
	@Field(58) 
	public int me_subpel_quality() {
		return this.io.getIntField(this, 58);
	}
	@Field(58) 
	public AVCodecContext me_subpel_quality(int me_subpel_quality) {
		this.io.setIntField(this, 58, me_subpel_quality);
		return this;
	}
	@Field(59) 
	public int dtg_active_format() {
		return this.io.getIntField(this, 59);
	}
	@Field(59) 
	public AVCodecContext dtg_active_format(int dtg_active_format) {
		this.io.setIntField(this, 59, dtg_active_format);
		return this;
	}
	@Field(60) 
	public int me_range() {
		return this.io.getIntField(this, 60);
	}
	@Field(60) 
	public AVCodecContext me_range(int me_range) {
		this.io.setIntField(this, 60, me_range);
		return this;
	}
	@Field(61) 
	public int intra_quant_bias() {
		return this.io.getIntField(this, 61);
	}
	@Field(61) 
	public AVCodecContext intra_quant_bias(int intra_quant_bias) {
		this.io.setIntField(this, 61, intra_quant_bias);
		return this;
	}
	@Field(62) 
	public int inter_quant_bias() {
		return this.io.getIntField(this, 62);
	}
	@Field(62) 
	public AVCodecContext inter_quant_bias(int inter_quant_bias) {
		this.io.setIntField(this, 62, inter_quant_bias);
		return this;
	}
	@Field(63) 
	public int slice_flags() {
		return this.io.getIntField(this, 63);
	}
	@Field(63) 
	public AVCodecContext slice_flags(int slice_flags) {
		this.io.setIntField(this, 63, slice_flags);
		return this;
	}
	@Field(64) 
	public int xvmc_acceleration() {
		return this.io.getIntField(this, 64);
	}
	@Field(64) 
	public AVCodecContext xvmc_acceleration(int xvmc_acceleration) {
		this.io.setIntField(this, 64, xvmc_acceleration);
		return this;
	}
	@Field(65) 
	public int mb_decision() {
		return this.io.getIntField(this, 65);
	}
	@Field(65) 
	public AVCodecContext mb_decision(int mb_decision) {
		this.io.setIntField(this, 65, mb_decision);
		return this;
	}
	/** C type : uint16_t* */
	@Field(66) 
	public Pointer<Short > intra_matrix() {
		return this.io.getPointerField(this, 66);
	}
	/** C type : uint16_t* */
	@Field(66) 
	public AVCodecContext intra_matrix(Pointer<Short > intra_matrix) {
		this.io.setPointerField(this, 66, intra_matrix);
		return this;
	}
	/** C type : uint16_t* */
	@Field(67) 
	public Pointer<Short > inter_matrix() {
		return this.io.getPointerField(this, 67);
	}
	/** C type : uint16_t* */
	@Field(67) 
	public AVCodecContext inter_matrix(Pointer<Short > inter_matrix) {
		this.io.setPointerField(this, 67, inter_matrix);
		return this;
	}
	@Field(68) 
	public int scenechange_threshold() {
		return this.io.getIntField(this, 68);
	}
	@Field(68) 
	public AVCodecContext scenechange_threshold(int scenechange_threshold) {
		this.io.setIntField(this, 68, scenechange_threshold);
		return this;
	}
	@Field(69) 
	public int noise_reduction() {
		return this.io.getIntField(this, 69);
	}
	@Field(69) 
	public AVCodecContext noise_reduction(int noise_reduction) {
		this.io.setIntField(this, 69, noise_reduction);
		return this;
	}
	@Field(70) 
	public int me_threshold() {
		return this.io.getIntField(this, 70);
	}
	@Field(70) 
	public AVCodecContext me_threshold(int me_threshold) {
		this.io.setIntField(this, 70, me_threshold);
		return this;
	}
	@Field(71) 
	public int mb_threshold() {
		return this.io.getIntField(this, 71);
	}
	@Field(71) 
	public AVCodecContext mb_threshold(int mb_threshold) {
		this.io.setIntField(this, 71, mb_threshold);
		return this;
	}
	@Field(72) 
	public int intra_dc_precision() {
		return this.io.getIntField(this, 72);
	}
	@Field(72) 
	public AVCodecContext intra_dc_precision(int intra_dc_precision) {
		this.io.setIntField(this, 72, intra_dc_precision);
		return this;
	}
	@Field(73) 
	public int skip_top() {
		return this.io.getIntField(this, 73);
	}
	@Field(73) 
	public AVCodecContext skip_top(int skip_top) {
		this.io.setIntField(this, 73, skip_top);
		return this;
	}
	@Field(74) 
	public int skip_bottom() {
		return this.io.getIntField(this, 74);
	}
	@Field(74) 
	public AVCodecContext skip_bottom(int skip_bottom) {
		this.io.setIntField(this, 74, skip_bottom);
		return this;
	}
	@Field(75) 
	public float border_masking() {
		return this.io.getFloatField(this, 75);
	}
	@Field(75) 
	public AVCodecContext border_masking(float border_masking) {
		this.io.setFloatField(this, 75, border_masking);
		return this;
	}
	@Field(76) 
	public int mb_lmin() {
		return this.io.getIntField(this, 76);
	}
	@Field(76) 
	public AVCodecContext mb_lmin(int mb_lmin) {
		this.io.setIntField(this, 76, mb_lmin);
		return this;
	}
	@Field(77) 
	public int mb_lmax() {
		return this.io.getIntField(this, 77);
	}
	@Field(77) 
	public AVCodecContext mb_lmax(int mb_lmax) {
		this.io.setIntField(this, 77, mb_lmax);
		return this;
	}
	@Field(78) 
	public int me_penalty_compensation() {
		return this.io.getIntField(this, 78);
	}
	@Field(78) 
	public AVCodecContext me_penalty_compensation(int me_penalty_compensation) {
		this.io.setIntField(this, 78, me_penalty_compensation);
		return this;
	}
	@Field(79) 
	public int bidir_refine() {
		return this.io.getIntField(this, 79);
	}
	@Field(79) 
	public AVCodecContext bidir_refine(int bidir_refine) {
		this.io.setIntField(this, 79, bidir_refine);
		return this;
	}
	@Field(80) 
	public int brd_scale() {
		return this.io.getIntField(this, 80);
	}
	@Field(80) 
	public AVCodecContext brd_scale(int brd_scale) {
		this.io.setIntField(this, 80, brd_scale);
		return this;
	}
	@Field(81) 
	public int keyint_min() {
		return this.io.getIntField(this, 81);
	}
	@Field(81) 
	public AVCodecContext keyint_min(int keyint_min) {
		this.io.setIntField(this, 81, keyint_min);
		return this;
	}
	@Field(82) 
	public int refs() {
		return this.io.getIntField(this, 82);
	}
	@Field(82) 
	public AVCodecContext refs(int refs) {
		this.io.setIntField(this, 82, refs);
		return this;
	}
	@Field(83) 
	public int chromaoffset() {
		return this.io.getIntField(this, 83);
	}
	@Field(83) 
	public AVCodecContext chromaoffset(int chromaoffset) {
		this.io.setIntField(this, 83, chromaoffset);
		return this;
	}
	@Field(84) 
	public int scenechange_factor() {
		return this.io.getIntField(this, 84);
	}
	@Field(84) 
	public AVCodecContext scenechange_factor(int scenechange_factor) {
		this.io.setIntField(this, 84, scenechange_factor);
		return this;
	}
	@Field(85) 
	public int mv0_threshold() {
		return this.io.getIntField(this, 85);
	}
	@Field(85) 
	public AVCodecContext mv0_threshold(int mv0_threshold) {
		this.io.setIntField(this, 85, mv0_threshold);
		return this;
	}
	@Field(86) 
	public int b_sensitivity() {
		return this.io.getIntField(this, 86);
	}
	@Field(86) 
	public AVCodecContext b_sensitivity(int b_sensitivity) {
		this.io.setIntField(this, 86, b_sensitivity);
		return this;
	}
	/** C type : AVColorPrimaries */
	@Field(87) 
	public IntValuedEnum<AVColorPrimaries > color_primaries() {
		return this.io.getEnumField(this, 87);
	}
	/** C type : AVColorPrimaries */
	@Field(87) 
	public AVCodecContext color_primaries(IntValuedEnum<AVColorPrimaries > color_primaries) {
		this.io.setEnumField(this, 87, color_primaries);
		return this;
	}
	/** C type : AVColorTransferCharacteristic */
	@Field(88) 
	public IntValuedEnum<AVColorTransferCharacteristic > color_trc() {
		return this.io.getEnumField(this, 88);
	}
	/** C type : AVColorTransferCharacteristic */
	@Field(88) 
	public AVCodecContext color_trc(IntValuedEnum<AVColorTransferCharacteristic > color_trc) {
		this.io.setEnumField(this, 88, color_trc);
		return this;
	}
	/** C type : AVColorSpace */
	@Field(89) 
	public IntValuedEnum<AVColorSpace > colorspace() {
		return this.io.getEnumField(this, 89);
	}
	/** C type : AVColorSpace */
	@Field(89) 
	public AVCodecContext colorspace(IntValuedEnum<AVColorSpace > colorspace) {
		this.io.setEnumField(this, 89, colorspace);
		return this;
	}
	/** C type : AVColorRange */
	@Field(90) 
	public IntValuedEnum<AVColorRange > color_range() {
		return this.io.getEnumField(this, 90);
	}
	/** C type : AVColorRange */
	@Field(90) 
	public AVCodecContext color_range(IntValuedEnum<AVColorRange > color_range) {
		this.io.setEnumField(this, 90, color_range);
		return this;
	}
	/** C type : AVChromaLocation */
	@Field(91) 
	public IntValuedEnum<AVChromaLocation > chroma_sample_location() {
		return this.io.getEnumField(this, 91);
	}
	/** C type : AVChromaLocation */
	@Field(91) 
	public AVCodecContext chroma_sample_location(IntValuedEnum<AVChromaLocation > chroma_sample_location) {
		this.io.setEnumField(this, 91, chroma_sample_location);
		return this;
	}
	@Field(92) 
	public int slices() {
		return this.io.getIntField(this, 92);
	}
	@Field(92) 
	public AVCodecContext slices(int slices) {
		this.io.setIntField(this, 92, slices);
		return this;
	}
	/** C type : AVFieldOrder */
	@Field(93) 
	public IntValuedEnum<AVFieldOrder > field_order() {
		return this.io.getEnumField(this, 93);
	}
	/** C type : AVFieldOrder */
	@Field(93) 
	public AVCodecContext field_order(IntValuedEnum<AVFieldOrder > field_order) {
		this.io.setEnumField(this, 93, field_order);
		return this;
	}
	/** < samples per second */
	@Field(94) 
	public int sample_rate() {
		return this.io.getIntField(this, 94);
	}
	/** < samples per second */
	@Field(94) 
	public AVCodecContext sample_rate(int sample_rate) {
		this.io.setIntField(this, 94, sample_rate);
		return this;
	}
	/** < number of audio channels */
	@Field(95) 
	public int channels() {
		return this.io.getIntField(this, 95);
	}
	/** < number of audio channels */
	@Field(95) 
	public AVCodecContext channels(int channels) {
		this.io.setIntField(this, 95, channels);
		return this;
	}
	/**
	 * < sample format<br>
	 * C type : AVSampleFormat
	 */
	@Field(96) 
	public IntValuedEnum<AVSampleFormat > sample_fmt() {
		return this.io.getEnumField(this, 96);
	}
	/**
	 * < sample format<br>
	 * C type : AVSampleFormat
	 */
	@Field(96) 
	public AVCodecContext sample_fmt(IntValuedEnum<AVSampleFormat > sample_fmt) {
		this.io.setEnumField(this, 96, sample_fmt);
		return this;
	}
	@Field(97) 
	public int frame_size() {
		return this.io.getIntField(this, 97);
	}
	@Field(97) 
	public AVCodecContext frame_size(int frame_size) {
		this.io.setIntField(this, 97, frame_size);
		return this;
	}
	@Field(98) 
	public int frame_number() {
		return this.io.getIntField(this, 98);
	}
	@Field(98) 
	public AVCodecContext frame_number(int frame_number) {
		this.io.setIntField(this, 98, frame_number);
		return this;
	}
	@Field(99) 
	public int block_align() {
		return this.io.getIntField(this, 99);
	}
	@Field(99) 
	public AVCodecContext block_align(int block_align) {
		this.io.setIntField(this, 99, block_align);
		return this;
	}
	@Field(100) 
	public int cutoff() {
		return this.io.getIntField(this, 100);
	}
	@Field(100) 
	public AVCodecContext cutoff(int cutoff) {
		this.io.setIntField(this, 100, cutoff);
		return this;
	}
	@Field(101) 
	public long channel_layout() {
		return this.io.getLongField(this, 101);
	}
	@Field(101) 
	public AVCodecContext channel_layout(long channel_layout) {
		this.io.setLongField(this, 101, channel_layout);
		return this;
	}
	@Field(102) 
	public long request_channel_layout() {
		return this.io.getLongField(this, 102);
	}
	@Field(102) 
	public AVCodecContext request_channel_layout(long request_channel_layout) {
		this.io.setLongField(this, 102, request_channel_layout);
		return this;
	}
	/** C type : AVAudioServiceType */
	@Field(103) 
	public IntValuedEnum<AVAudioServiceType > audio_service_type() {
		return this.io.getEnumField(this, 103);
	}
	/** C type : AVAudioServiceType */
	@Field(103) 
	public AVCodecContext audio_service_type(IntValuedEnum<AVAudioServiceType > audio_service_type) {
		this.io.setEnumField(this, 103, audio_service_type);
		return this;
	}
	/** C type : AVSampleFormat */
	@Field(104) 
	public IntValuedEnum<AVSampleFormat > request_sample_fmt() {
		return this.io.getEnumField(this, 104);
	}
	/** C type : AVSampleFormat */
	@Field(104) 
	public AVCodecContext request_sample_fmt(IntValuedEnum<AVSampleFormat > request_sample_fmt) {
		this.io.setEnumField(this, 104, request_sample_fmt);
		return this;
	}
	/** C type : get_buffer2_callback* */
	@Field(105) 
	public Pointer<get_buffer2_callback > get_buffer2() {
		return this.io.getPointerField(this, 105);
	}
	/** C type : get_buffer2_callback* */
	@Field(105) 
	public AVCodecContext get_buffer2(Pointer<get_buffer2_callback > get_buffer2) {
		this.io.setPointerField(this, 105, get_buffer2);
		return this;
	}
	@Field(106) 
	public int refcounted_frames() {
		return this.io.getIntField(this, 106);
	}
	@Field(106) 
	public AVCodecContext refcounted_frames(int refcounted_frames) {
		this.io.setIntField(this, 106, refcounted_frames);
		return this;
	}
	/** < amount of qscale change between easy & hard scenes (0.0-1.0) */
	@Field(107) 
	public float qcompress() {
		return this.io.getFloatField(this, 107);
	}
	/** < amount of qscale change between easy & hard scenes (0.0-1.0) */
	@Field(107) 
	public AVCodecContext qcompress(float qcompress) {
		this.io.setFloatField(this, 107, qcompress);
		return this;
	}
	/** < amount of qscale smoothing over time (0.0-1.0) */
	@Field(108) 
	public float qblur() {
		return this.io.getFloatField(this, 108);
	}
	/** < amount of qscale smoothing over time (0.0-1.0) */
	@Field(108) 
	public AVCodecContext qblur(float qblur) {
		this.io.setFloatField(this, 108, qblur);
		return this;
	}
	@Field(109) 
	public int qmin() {
		return this.io.getIntField(this, 109);
	}
	@Field(109) 
	public AVCodecContext qmin(int qmin) {
		this.io.setIntField(this, 109, qmin);
		return this;
	}
	@Field(110) 
	public int qmax() {
		return this.io.getIntField(this, 110);
	}
	@Field(110) 
	public AVCodecContext qmax(int qmax) {
		this.io.setIntField(this, 110, qmax);
		return this;
	}
	@Field(111) 
	public int max_qdiff() {
		return this.io.getIntField(this, 111);
	}
	@Field(111) 
	public AVCodecContext max_qdiff(int max_qdiff) {
		this.io.setIntField(this, 111, max_qdiff);
		return this;
	}
	@Field(112) 
	public float rc_qsquish() {
		return this.io.getFloatField(this, 112);
	}
	@Field(112) 
	public AVCodecContext rc_qsquish(float rc_qsquish) {
		this.io.setFloatField(this, 112, rc_qsquish);
		return this;
	}
	@Field(113) 
	public float rc_qmod_amp() {
		return this.io.getFloatField(this, 113);
	}
	@Field(113) 
	public AVCodecContext rc_qmod_amp(float rc_qmod_amp) {
		this.io.setFloatField(this, 113, rc_qmod_amp);
		return this;
	}
	@Field(114) 
	public int rc_qmod_freq() {
		return this.io.getIntField(this, 114);
	}
	@Field(114) 
	public AVCodecContext rc_qmod_freq(int rc_qmod_freq) {
		this.io.setIntField(this, 114, rc_qmod_freq);
		return this;
	}
	@Field(115) 
	public int rc_buffer_size() {
		return this.io.getIntField(this, 115);
	}
	@Field(115) 
	public AVCodecContext rc_buffer_size(int rc_buffer_size) {
		this.io.setIntField(this, 115, rc_buffer_size);
		return this;
	}
	@Field(116) 
	public int rc_override_count() {
		return this.io.getIntField(this, 116);
	}
	@Field(116) 
	public AVCodecContext rc_override_count(int rc_override_count) {
		this.io.setIntField(this, 116, rc_override_count);
		return this;
	}
	/** C type : RcOverride* */
	@Field(117) 
	public Pointer<RcOverride > rc_override() {
		return this.io.getPointerField(this, 117);
	}
	/** C type : RcOverride* */
	@Field(117) 
	public AVCodecContext rc_override(Pointer<RcOverride > rc_override) {
		this.io.setPointerField(this, 117, rc_override);
		return this;
	}
	/** C type : const char* */
	@Field(118) 
	public Pointer<Byte > rc_eq() {
		return this.io.getPointerField(this, 118);
	}
	/** C type : const char* */
	@Field(118) 
	public AVCodecContext rc_eq(Pointer<Byte > rc_eq) {
		this.io.setPointerField(this, 118, rc_eq);
		return this;
	}
	@Field(119) 
	public long rc_max_rate() {
		return this.io.getLongField(this, 119);
	}
	@Field(119) 
	public AVCodecContext rc_max_rate(long rc_max_rate) {
		this.io.setLongField(this, 119, rc_max_rate);
		return this;
	}
	@Field(120) 
	public long rc_min_rate() {
		return this.io.getLongField(this, 120);
	}
	@Field(120) 
	public AVCodecContext rc_min_rate(long rc_min_rate) {
		this.io.setLongField(this, 120, rc_min_rate);
		return this;
	}
	@Field(121) 
	public float rc_buffer_aggressivity() {
		return this.io.getFloatField(this, 121);
	}
	@Field(121) 
	public AVCodecContext rc_buffer_aggressivity(float rc_buffer_aggressivity) {
		this.io.setFloatField(this, 121, rc_buffer_aggressivity);
		return this;
	}
	@Field(122) 
	public float rc_initial_cplx() {
		return this.io.getFloatField(this, 122);
	}
	@Field(122) 
	public AVCodecContext rc_initial_cplx(float rc_initial_cplx) {
		this.io.setFloatField(this, 122, rc_initial_cplx);
		return this;
	}
	@Field(123) 
	public float rc_max_available_vbv_use() {
		return this.io.getFloatField(this, 123);
	}
	@Field(123) 
	public AVCodecContext rc_max_available_vbv_use(float rc_max_available_vbv_use) {
		this.io.setFloatField(this, 123, rc_max_available_vbv_use);
		return this;
	}
	@Field(124) 
	public float rc_min_vbv_overflow_use() {
		return this.io.getFloatField(this, 124);
	}
	@Field(124) 
	public AVCodecContext rc_min_vbv_overflow_use(float rc_min_vbv_overflow_use) {
		this.io.setFloatField(this, 124, rc_min_vbv_overflow_use);
		return this;
	}
	@Field(125) 
	public int rc_initial_buffer_occupancy() {
		return this.io.getIntField(this, 125);
	}
	@Field(125) 
	public AVCodecContext rc_initial_buffer_occupancy(int rc_initial_buffer_occupancy) {
		this.io.setIntField(this, 125, rc_initial_buffer_occupancy);
		return this;
	}
	@Field(126) 
	public int coder_type() {
		return this.io.getIntField(this, 126);
	}
	@Field(126) 
	public AVCodecContext coder_type(int coder_type) {
		this.io.setIntField(this, 126, coder_type);
		return this;
	}
	@Field(127) 
	public int context_model() {
		return this.io.getIntField(this, 127);
	}
	@Field(127) 
	public AVCodecContext context_model(int context_model) {
		this.io.setIntField(this, 127, context_model);
		return this;
	}
	@Field(128) 
	public int lmin() {
		return this.io.getIntField(this, 128);
	}
	@Field(128) 
	public AVCodecContext lmin(int lmin) {
		this.io.setIntField(this, 128, lmin);
		return this;
	}
	@Field(129) 
	public int lmax() {
		return this.io.getIntField(this, 129);
	}
	@Field(129) 
	public AVCodecContext lmax(int lmax) {
		this.io.setIntField(this, 129, lmax);
		return this;
	}
	@Field(130) 
	public int frame_skip_threshold() {
		return this.io.getIntField(this, 130);
	}
	@Field(130) 
	public AVCodecContext frame_skip_threshold(int frame_skip_threshold) {
		this.io.setIntField(this, 130, frame_skip_threshold);
		return this;
	}
	@Field(131) 
	public int frame_skip_factor() {
		return this.io.getIntField(this, 131);
	}
	@Field(131) 
	public AVCodecContext frame_skip_factor(int frame_skip_factor) {
		this.io.setIntField(this, 131, frame_skip_factor);
		return this;
	}
	@Field(132) 
	public int frame_skip_exp() {
		return this.io.getIntField(this, 132);
	}
	@Field(132) 
	public AVCodecContext frame_skip_exp(int frame_skip_exp) {
		this.io.setIntField(this, 132, frame_skip_exp);
		return this;
	}
	@Field(133) 
	public int frame_skip_cmp() {
		return this.io.getIntField(this, 133);
	}
	@Field(133) 
	public AVCodecContext frame_skip_cmp(int frame_skip_cmp) {
		this.io.setIntField(this, 133, frame_skip_cmp);
		return this;
	}
	@Field(134) 
	public int trellis() {
		return this.io.getIntField(this, 134);
	}
	@Field(134) 
	public AVCodecContext trellis(int trellis) {
		this.io.setIntField(this, 134, trellis);
		return this;
	}
	@Field(135) 
	public int min_prediction_order() {
		return this.io.getIntField(this, 135);
	}
	@Field(135) 
	public AVCodecContext min_prediction_order(int min_prediction_order) {
		this.io.setIntField(this, 135, min_prediction_order);
		return this;
	}
	@Field(136) 
	public int max_prediction_order() {
		return this.io.getIntField(this, 136);
	}
	@Field(136) 
	public AVCodecContext max_prediction_order(int max_prediction_order) {
		this.io.setIntField(this, 136, max_prediction_order);
		return this;
	}
	@Field(137) 
	public long timecode_frame_start() {
		return this.io.getLongField(this, 137);
	}
	@Field(137) 
	public AVCodecContext timecode_frame_start(long timecode_frame_start) {
		this.io.setLongField(this, 137, timecode_frame_start);
		return this;
	}
	/** C type : rtp_callback_callback* */
	@Field(138) 
	public Pointer<rtp_callback_callback > rtp_callback() {
		return this.io.getPointerField(this, 138);
	}
	/** C type : rtp_callback_callback* */
	@Field(138) 
	public AVCodecContext rtp_callback(Pointer<rtp_callback_callback > rtp_callback) {
		this.io.setPointerField(this, 138, rtp_callback);
		return this;
	}
	/** The size of the RTP payload: the coder will */
	@Field(139) 
	public int rtp_payload_size() {
		return this.io.getIntField(this, 139);
	}
	/** The size of the RTP payload: the coder will */
	@Field(139) 
	public AVCodecContext rtp_payload_size(int rtp_payload_size) {
		this.io.setIntField(this, 139, rtp_payload_size);
		return this;
	}
	@Field(140) 
	public int mv_bits() {
		return this.io.getIntField(this, 140);
	}
	@Field(140) 
	public AVCodecContext mv_bits(int mv_bits) {
		this.io.setIntField(this, 140, mv_bits);
		return this;
	}
	@Field(141) 
	public int header_bits() {
		return this.io.getIntField(this, 141);
	}
	@Field(141) 
	public AVCodecContext header_bits(int header_bits) {
		this.io.setIntField(this, 141, header_bits);
		return this;
	}
	@Field(142) 
	public int i_tex_bits() {
		return this.io.getIntField(this, 142);
	}
	@Field(142) 
	public AVCodecContext i_tex_bits(int i_tex_bits) {
		this.io.setIntField(this, 142, i_tex_bits);
		return this;
	}
	@Field(143) 
	public int p_tex_bits() {
		return this.io.getIntField(this, 143);
	}
	@Field(143) 
	public AVCodecContext p_tex_bits(int p_tex_bits) {
		this.io.setIntField(this, 143, p_tex_bits);
		return this;
	}
	@Field(144) 
	public int i_count() {
		return this.io.getIntField(this, 144);
	}
	@Field(144) 
	public AVCodecContext i_count(int i_count) {
		this.io.setIntField(this, 144, i_count);
		return this;
	}
	@Field(145) 
	public int p_count() {
		return this.io.getIntField(this, 145);
	}
	@Field(145) 
	public AVCodecContext p_count(int p_count) {
		this.io.setIntField(this, 145, p_count);
		return this;
	}
	@Field(146) 
	public int skip_count() {
		return this.io.getIntField(this, 146);
	}
	@Field(146) 
	public AVCodecContext skip_count(int skip_count) {
		this.io.setIntField(this, 146, skip_count);
		return this;
	}
	@Field(147) 
	public int misc_bits() {
		return this.io.getIntField(this, 147);
	}
	@Field(147) 
	public AVCodecContext misc_bits(int misc_bits) {
		this.io.setIntField(this, 147, misc_bits);
		return this;
	}
	@Field(148) 
	public int frame_bits() {
		return this.io.getIntField(this, 148);
	}
	@Field(148) 
	public AVCodecContext frame_bits(int frame_bits) {
		this.io.setIntField(this, 148, frame_bits);
		return this;
	}
	/** C type : char* */
	@Field(149) 
	public Pointer<Byte > stats_out() {
		return this.io.getPointerField(this, 149);
	}
	/** C type : char* */
	@Field(149) 
	public AVCodecContext stats_out(Pointer<Byte > stats_out) {
		this.io.setPointerField(this, 149, stats_out);
		return this;
	}
	/** C type : char* */
	@Field(150) 
	public Pointer<Byte > stats_in() {
		return this.io.getPointerField(this, 150);
	}
	/** C type : char* */
	@Field(150) 
	public AVCodecContext stats_in(Pointer<Byte > stats_in) {
		this.io.setPointerField(this, 150, stats_in);
		return this;
	}
	@Field(151) 
	public int workaround_bugs() {
		return this.io.getIntField(this, 151);
	}
	@Field(151) 
	public AVCodecContext workaround_bugs(int workaround_bugs) {
		this.io.setIntField(this, 151, workaround_bugs);
		return this;
	}
	@Field(152) 
	public int strict_std_compliance() {
		return this.io.getIntField(this, 152);
	}
	@Field(152) 
	public AVCodecContext strict_std_compliance(int strict_std_compliance) {
		this.io.setIntField(this, 152, strict_std_compliance);
		return this;
	}
	@Field(153) 
	public int error_concealment() {
		return this.io.getIntField(this, 153);
	}
	@Field(153) 
	public AVCodecContext error_concealment(int error_concealment) {
		this.io.setIntField(this, 153, error_concealment);
		return this;
	}
	@Field(154) 
	public int debug() {
		return this.io.getIntField(this, 154);
	}
	@Field(154) 
	public AVCodecContext debug(int debug) {
		this.io.setIntField(this, 154, debug);
		return this;
	}
	@Field(155) 
	public int debug_mv() {
		return this.io.getIntField(this, 155);
	}
	@Field(155) 
	public AVCodecContext debug_mv(int debug_mv) {
		this.io.setIntField(this, 155, debug_mv);
		return this;
	}
	@Field(156) 
	public int err_recognition() {
		return this.io.getIntField(this, 156);
	}
	@Field(156) 
	public AVCodecContext err_recognition(int err_recognition) {
		this.io.setIntField(this, 156, err_recognition);
		return this;
	}
	@Field(157) 
	public long reordered_opaque() {
		return this.io.getLongField(this, 157);
	}
	@Field(157) 
	public AVCodecContext reordered_opaque(long reordered_opaque) {
		this.io.setLongField(this, 157, reordered_opaque);
		return this;
	}
	/** C type : AVHWAccel* */
	@Field(158) 
	public Pointer<AVHWAccel > hwaccel() {
		return this.io.getPointerField(this, 158);
	}
	/** C type : AVHWAccel* */
	@Field(158) 
	public AVCodecContext hwaccel(Pointer<AVHWAccel > hwaccel) {
		this.io.setPointerField(this, 158, hwaccel);
		return this;
	}
	/** C type : void* */
	@Field(159) 
	public Pointer<? > hwaccel_context() {
		return this.io.getPointerField(this, 159);
	}
	/** C type : void* */
	@Field(159) 
	public AVCodecContext hwaccel_context(Pointer<? > hwaccel_context) {
		this.io.setPointerField(this, 159, hwaccel_context);
		return this;
	}
	/** C type : uint64_t[8] */
	@Array({8}) 
	@Field(160) 
	public Pointer<Long > error() {
		return this.io.getPointerField(this, 160);
	}
	@Field(161) 
	public int dct_algo() {
		return this.io.getIntField(this, 161);
	}
	@Field(161) 
	public AVCodecContext dct_algo(int dct_algo) {
		this.io.setIntField(this, 161, dct_algo);
		return this;
	}
	@Field(162) 
	public int idct_algo() {
		return this.io.getIntField(this, 162);
	}
	@Field(162) 
	public AVCodecContext idct_algo(int idct_algo) {
		this.io.setIntField(this, 162, idct_algo);
		return this;
	}
	@Field(163) 
	public int bits_per_coded_sample() {
		return this.io.getIntField(this, 163);
	}
	@Field(163) 
	public AVCodecContext bits_per_coded_sample(int bits_per_coded_sample) {
		this.io.setIntField(this, 163, bits_per_coded_sample);
		return this;
	}
	@Field(164) 
	public int bits_per_raw_sample() {
		return this.io.getIntField(this, 164);
	}
	@Field(164) 
	public AVCodecContext bits_per_raw_sample(int bits_per_raw_sample) {
		this.io.setIntField(this, 164, bits_per_raw_sample);
		return this;
	}
	@Field(165) 
	public int lowres() {
		return this.io.getIntField(this, 165);
	}
	@Field(165) 
	public AVCodecContext lowres(int lowres) {
		this.io.setIntField(this, 165, lowres);
		return this;
	}
	/** C type : AVFrame* */
	@Field(166) 
	public Pointer<AVFrame > coded_frame() {
		return this.io.getPointerField(this, 166);
	}
	/** C type : AVFrame* */
	@Field(166) 
	public AVCodecContext coded_frame(Pointer<AVFrame > coded_frame) {
		this.io.setPointerField(this, 166, coded_frame);
		return this;
	}
	@Field(167) 
	public int thread_count() {
		return this.io.getIntField(this, 167);
	}
	@Field(167) 
	public AVCodecContext thread_count(int thread_count) {
		this.io.setIntField(this, 167, thread_count);
		return this;
	}
	@Field(168) 
	public int thread_type() {
		return this.io.getIntField(this, 168);
	}
	@Field(168) 
	public AVCodecContext thread_type(int thread_type) {
		this.io.setIntField(this, 168, thread_type);
		return this;
	}
	@Field(169) 
	public int active_thread_type() {
		return this.io.getIntField(this, 169);
	}
	@Field(169) 
	public AVCodecContext active_thread_type(int active_thread_type) {
		this.io.setIntField(this, 169, active_thread_type);
		return this;
	}
	@Field(170) 
	public int thread_safe_callbacks() {
		return this.io.getIntField(this, 170);
	}
	@Field(170) 
	public AVCodecContext thread_safe_callbacks(int thread_safe_callbacks) {
		this.io.setIntField(this, 170, thread_safe_callbacks);
		return this;
	}
	/** C type : execute_callback* */
	@Field(171) 
	public Pointer<execute_callback > execute() {
		return this.io.getPointerField(this, 171);
	}
	/** C type : execute_callback* */
	@Field(171) 
	public AVCodecContext execute(Pointer<execute_callback > execute) {
		this.io.setPointerField(this, 171, execute);
		return this;
	}
	/** C type : execute2_callback* */
	@Field(172) 
	public Pointer<execute2_callback > execute2() {
		return this.io.getPointerField(this, 172);
	}
	/** C type : execute2_callback* */
	@Field(172) 
	public AVCodecContext execute2(Pointer<execute2_callback > execute2) {
		this.io.setPointerField(this, 172, execute2);
		return this;
	}
	@Field(173) 
	public int nsse_weight() {
		return this.io.getIntField(this, 173);
	}
	@Field(173) 
	public AVCodecContext nsse_weight(int nsse_weight) {
		this.io.setIntField(this, 173, nsse_weight);
		return this;
	}
	@Field(174) 
	public int profile() {
		return this.io.getIntField(this, 174);
	}
	@Field(174) 
	public AVCodecContext profile(int profile) {
		this.io.setIntField(this, 174, profile);
		return this;
	}
	@Field(175) 
	public int level() {
		return this.io.getIntField(this, 175);
	}
	@Field(175) 
	public AVCodecContext level(int level) {
		this.io.setIntField(this, 175, level);
		return this;
	}
	/** C type : AVDiscard */
	@Field(176) 
	public IntValuedEnum<AVDiscard > skip_loop_filter() {
		return this.io.getEnumField(this, 176);
	}
	/** C type : AVDiscard */
	@Field(176) 
	public AVCodecContext skip_loop_filter(IntValuedEnum<AVDiscard > skip_loop_filter) {
		this.io.setEnumField(this, 176, skip_loop_filter);
		return this;
	}
	/** C type : AVDiscard */
	@Field(177) 
	public IntValuedEnum<AVDiscard > skip_idct() {
		return this.io.getEnumField(this, 177);
	}
	/** C type : AVDiscard */
	@Field(177) 
	public AVCodecContext skip_idct(IntValuedEnum<AVDiscard > skip_idct) {
		this.io.setEnumField(this, 177, skip_idct);
		return this;
	}
	/** C type : AVDiscard */
	@Field(178) 
	public IntValuedEnum<AVDiscard > skip_frame() {
		return this.io.getEnumField(this, 178);
	}
	/** C type : AVDiscard */
	@Field(178) 
	public AVCodecContext skip_frame(IntValuedEnum<AVDiscard > skip_frame) {
		this.io.setEnumField(this, 178, skip_frame);
		return this;
	}
	/** C type : uint8_t* */
	@Field(179) 
	public Pointer<Byte > subtitle_header() {
		return this.io.getPointerField(this, 179);
	}
	/** C type : uint8_t* */
	@Field(179) 
	public AVCodecContext subtitle_header(Pointer<Byte > subtitle_header) {
		this.io.setPointerField(this, 179, subtitle_header);
		return this;
	}
	@Field(180) 
	public int subtitle_header_size() {
		return this.io.getIntField(this, 180);
	}
	@Field(180) 
	public AVCodecContext subtitle_header_size(int subtitle_header_size) {
		this.io.setIntField(this, 180, subtitle_header_size);
		return this;
	}
	@Field(181) 
	public int error_rate() {
		return this.io.getIntField(this, 181);
	}
	@Field(181) 
	public AVCodecContext error_rate(int error_rate) {
		this.io.setIntField(this, 181, error_rate);
		return this;
	}
	@Field(182) 
	public long vbv_delay() {
		return this.io.getLongField(this, 182);
	}
	@Field(182) 
	public AVCodecContext vbv_delay(long vbv_delay) {
		this.io.setLongField(this, 182, vbv_delay);
		return this;
	}
	@Field(183) 
	public int side_data_only_packets() {
		return this.io.getIntField(this, 183);
	}
	@Field(183) 
	public AVCodecContext side_data_only_packets(int side_data_only_packets) {
		this.io.setIntField(this, 183, side_data_only_packets);
		return this;
	}
	@Field(184) 
	public int initial_padding() {
		return this.io.getIntField(this, 184);
	}
	@Field(184) 
	public AVCodecContext initial_padding(int initial_padding) {
		this.io.setIntField(this, 184, initial_padding);
		return this;
	}
	/** C type : AVRational */
	@Field(185) 
	public AVRational framerate() {
		return this.io.getNativeObjectField(this, 185);
	}
	/** C type : AVRational */
	@Field(185) 
	public AVCodecContext framerate(AVRational framerate) {
		this.io.setNativeObjectField(this, 185, framerate);
		return this;
	}
	/** C type : AVPixelFormat */
	@Field(186) 
	public IntValuedEnum<AVPixelFormat > sw_pix_fmt() {
		return this.io.getEnumField(this, 186);
	}
	/** C type : AVPixelFormat */
	@Field(186) 
	public AVCodecContext sw_pix_fmt(IntValuedEnum<AVPixelFormat > sw_pix_fmt) {
		this.io.setEnumField(this, 186, sw_pix_fmt);
		return this;
	}
	/** C type : AVRational */
	@Field(187) 
	public AVRational pkt_timebase() {
		return this.io.getNativeObjectField(this, 187);
	}
	/** C type : AVRational */
	@Field(187) 
	public AVCodecContext pkt_timebase(AVRational pkt_timebase) {
		this.io.setNativeObjectField(this, 187, pkt_timebase);
		return this;
	}
	/** C type : const AVCodecDescriptor* */
	@Field(188) 
	public Pointer<AVCodecDescriptor > codec_descriptor() {
		return this.io.getPointerField(this, 188);
	}
	/** C type : const AVCodecDescriptor* */
	@Field(188) 
	public AVCodecContext codec_descriptor(Pointer<AVCodecDescriptor > codec_descriptor) {
		this.io.setPointerField(this, 188, codec_descriptor);
		return this;
	}
	/** Number of incorrect PTS values so far */
	@Field(189) 
	public long pts_correction_num_faulty_pts() {
		return this.io.getLongField(this, 189);
	}
	/** Number of incorrect PTS values so far */
	@Field(189) 
	public AVCodecContext pts_correction_num_faulty_pts(long pts_correction_num_faulty_pts) {
		this.io.setLongField(this, 189, pts_correction_num_faulty_pts);
		return this;
	}
	/** Number of incorrect DTS values so far */
	@Field(190) 
	public long pts_correction_num_faulty_dts() {
		return this.io.getLongField(this, 190);
	}
	/** Number of incorrect DTS values so far */
	@Field(190) 
	public AVCodecContext pts_correction_num_faulty_dts(long pts_correction_num_faulty_dts) {
		this.io.setLongField(this, 190, pts_correction_num_faulty_dts);
		return this;
	}
	/** PTS of the last frame */
	@Field(191) 
	public long pts_correction_last_pts() {
		return this.io.getLongField(this, 191);
	}
	/** PTS of the last frame */
	@Field(191) 
	public AVCodecContext pts_correction_last_pts(long pts_correction_last_pts) {
		this.io.setLongField(this, 191, pts_correction_last_pts);
		return this;
	}
	/** DTS of the last frame */
	@Field(192) 
	public long pts_correction_last_dts() {
		return this.io.getLongField(this, 192);
	}
	/** DTS of the last frame */
	@Field(192) 
	public AVCodecContext pts_correction_last_dts(long pts_correction_last_dts) {
		this.io.setLongField(this, 192, pts_correction_last_dts);
		return this;
	}
	/** C type : char* */
	@Field(193) 
	public Pointer<Byte > sub_charenc() {
		return this.io.getPointerField(this, 193);
	}
	/** C type : char* */
	@Field(193) 
	public AVCodecContext sub_charenc(Pointer<Byte > sub_charenc) {
		this.io.setPointerField(this, 193, sub_charenc);
		return this;
	}
	@Field(194) 
	public int sub_charenc_mode() {
		return this.io.getIntField(this, 194);
	}
	@Field(194) 
	public AVCodecContext sub_charenc_mode(int sub_charenc_mode) {
		this.io.setIntField(this, 194, sub_charenc_mode);
		return this;
	}
	@Field(195) 
	public int skip_alpha() {
		return this.io.getIntField(this, 195);
	}
	@Field(195) 
	public AVCodecContext skip_alpha(int skip_alpha) {
		this.io.setIntField(this, 195, skip_alpha);
		return this;
	}
	@Field(196) 
	public int seek_preroll() {
		return this.io.getIntField(this, 196);
	}
	@Field(196) 
	public AVCodecContext seek_preroll(int seek_preroll) {
		this.io.setIntField(this, 196, seek_preroll);
		return this;
	}
	/** C type : uint16_t* */
	@Field(197) 
	public Pointer<Short > chroma_intra_matrix() {
		return this.io.getPointerField(this, 197);
	}
	/** C type : uint16_t* */
	@Field(197) 
	public AVCodecContext chroma_intra_matrix(Pointer<Short > chroma_intra_matrix) {
		this.io.setPointerField(this, 197, chroma_intra_matrix);
		return this;
	}
	/** C type : uint8_t* */
	@Field(198) 
	public Pointer<Byte > dump_separator() {
		return this.io.getPointerField(this, 198);
	}
	/** C type : uint8_t* */
	@Field(198) 
	public AVCodecContext dump_separator(Pointer<Byte > dump_separator) {
		this.io.setPointerField(this, 198, dump_separator);
		return this;
	}
	/** C type : char* */
	@Field(199) 
	public Pointer<Byte > codec_whitelist() {
		return this.io.getPointerField(this, 199);
	}
	/** C type : char* */
	@Field(199) 
	public AVCodecContext codec_whitelist(Pointer<Byte > codec_whitelist) {
		this.io.setPointerField(this, 199, codec_whitelist);
		return this;
	}
	@Field(200) 
	public int properties() {
		return this.io.getIntField(this, 200);
	}
	@Field(200) 
	public AVCodecContext properties(int properties) {
		this.io.setIntField(this, 200, properties);
		return this;
	}
	/** C type : AVPacketSideData* */
	@Field(201) 
	public Pointer<AVPacketSideData > coded_side_data() {
		return this.io.getPointerField(this, 201);
	}
	/** C type : AVPacketSideData* */
	@Field(201) 
	public AVCodecContext coded_side_data(Pointer<AVPacketSideData > coded_side_data) {
		this.io.setPointerField(this, 201, coded_side_data);
		return this;
	}
	@Field(202) 
	public int nb_coded_side_data() {
		return this.io.getIntField(this, 202);
	}
	@Field(202) 
	public AVCodecContext nb_coded_side_data(int nb_coded_side_data) {
		this.io.setIntField(this, 202, nb_coded_side_data);
		return this;
	}
	/** C type : AVBufferRef* */
	@Field(203) 
	public Pointer<AVBufferRef > hw_frames_ctx() {
		return this.io.getPointerField(this, 203);
	}
	/** C type : AVBufferRef* */
	@Field(203) 
	public AVCodecContext hw_frames_ctx(Pointer<AVBufferRef > hw_frames_ctx) {
		this.io.setPointerField(this, 203, hw_frames_ctx);
		return this;
	}
	@Field(204) 
	public int sub_text_format() {
		return this.io.getIntField(this, 204);
	}
	@Field(204) 
	public AVCodecContext sub_text_format(int sub_text_format) {
		this.io.setIntField(this, 204, sub_text_format);
		return this;
	}
	@Field(205) 
	public int trailing_padding() {
		return this.io.getIntField(this, 205);
	}
	@Field(205) 
	public AVCodecContext trailing_padding(int trailing_padding) {
		this.io.setIntField(this, 205, trailing_padding);
		return this;
	}
	@Field(206) 
	public long max_pixels() {
		return this.io.getLongField(this, 206);
	}
	@Field(206) 
	public AVCodecContext max_pixels(long max_pixels) {
		this.io.setLongField(this, 206, max_pixels);
		return this;
	}
	/** C type : AVBufferRef* */
	@Field(207) 
	public Pointer<AVBufferRef > hw_device_ctx() {
		return this.io.getPointerField(this, 207);
	}
	/** C type : AVBufferRef* */
	@Field(207) 
	public AVCodecContext hw_device_ctx(Pointer<AVBufferRef > hw_device_ctx) {
		this.io.setPointerField(this, 207, hw_device_ctx);
		return this;
	}
	@Field(208) 
	public int hwaccel_flags() {
		return this.io.getIntField(this, 208);
	}
	@Field(208) 
	public AVCodecContext hwaccel_flags(int hwaccel_flags) {
		this.io.setIntField(this, 208, hwaccel_flags);
		return this;
	}
	/** <i>native declaration : .\libavcodec\avcodec.h:904</i> */
	public static abstract class draw_horiz_band_callback extends Callback<draw_horiz_band_callback > {
		public void apply(Pointer<AVCodecContext > s, Pointer<AVFrame > src, Pointer<Integer > offset, int y, int type, int height) {
			apply(Pointer.getPeer(s), Pointer.getPeer(src), Pointer.getPeer(offset), y, type, height);
		}
		public void apply(@Ptr long s, @Ptr long src, @Ptr long offset, int y, int type, int height) {
			apply((Pointer)Pointer.pointerToAddress(s, AVCodecContext.class), (Pointer)Pointer.pointerToAddress(src, AVFrame.class), (Pointer)Pointer.pointerToAddress(offset, Integer.class), y, type, height);
		}
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:923</i> */
	public static abstract class get_buffer2_callback extends Callback<get_buffer2_callback > {
		public int apply(Pointer<AVCodecContext > s, Pointer<AVFrame > frame, int flags) {
			return apply(Pointer.getPeer(s), Pointer.getPeer(frame), flags);
		}
		public int apply(@Ptr long s, @Ptr long frame, int flags) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVCodecContext.class), (Pointer)Pointer.pointerToAddress(frame, AVFrame.class), flags);
		}
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:924</i> */
	public static abstract class rtp_callback_callback extends Callback<rtp_callback_callback > {
		public void apply(Pointer<AVCodecContext > avctx, Pointer<? > data, int size, int mb_nb) {
			apply(Pointer.getPeer(avctx), Pointer.getPeer(data), size, mb_nb);
		}
		public void apply(@Ptr long avctx, @Ptr long data, int size, int mb_nb) {
			apply((Pointer)Pointer.pointerToAddress(avctx, AVCodecContext.class), Pointer.pointerToAddress(data), size, mb_nb);
		}
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:925</i> */
	public static abstract class execute_callback_func_callback extends Callback<execute_callback_func_callback > {
		public int apply(Pointer<AVCodecContext > c2, Pointer<? > arg) {
			return apply(Pointer.getPeer(c2), Pointer.getPeer(arg));
		}
		public int apply(@Ptr long c2, @Ptr long arg) {
			return apply((Pointer)Pointer.pointerToAddress(c2, AVCodecContext.class), Pointer.pointerToAddress(arg));
		}
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:926</i> */
	public static abstract class execute_callback extends Callback<execute_callback > {
		public int apply(Pointer<AVCodecContext > c, Pointer<execute_callback_func_callback > func, Pointer<? > arg2, Pointer<Integer > ret, int count, int size) {
			return apply(Pointer.getPeer(c), Pointer.getPeer(func), Pointer.getPeer(arg2), Pointer.getPeer(ret), count, size);
		}
		public int apply(@Ptr long c, @Ptr long func, @Ptr long arg2, @Ptr long ret, int count, int size) {
			return apply((Pointer)Pointer.pointerToAddress(c, AVCodecContext.class), (Pointer)Pointer.pointerToAddress(func, execute_callback_func_callback.class), Pointer.pointerToAddress(arg2), (Pointer)Pointer.pointerToAddress(ret, Integer.class), count, size);
		}
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:927</i> */
	public static abstract class execute2_callback_func_callback extends Callback<execute2_callback_func_callback > {
		public int apply(Pointer<AVCodecContext > c2, Pointer<? > arg, int jobnr, int threadnr) {
			return apply(Pointer.getPeer(c2), Pointer.getPeer(arg), jobnr, threadnr);
		}
		public int apply(@Ptr long c2, @Ptr long arg, int jobnr, int threadnr) {
			return apply((Pointer)Pointer.pointerToAddress(c2, AVCodecContext.class), Pointer.pointerToAddress(arg), jobnr, threadnr);
		}
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:928</i> */
	public static abstract class execute2_callback extends Callback<execute2_callback > {
		public int apply(Pointer<AVCodecContext > c, Pointer<execute2_callback_func_callback > func, Pointer<? > arg2, Pointer<Integer > ret, int count) {
			return apply(Pointer.getPeer(c), Pointer.getPeer(func), Pointer.getPeer(arg2), Pointer.getPeer(ret), count);
		}
		public int apply(@Ptr long c, @Ptr long func, @Ptr long arg2, @Ptr long ret, int count) {
			return apply((Pointer)Pointer.pointerToAddress(c, AVCodecContext.class), (Pointer)Pointer.pointerToAddress(func, execute2_callback_func_callback.class), Pointer.pointerToAddress(arg2), (Pointer)Pointer.pointerToAddress(ret, Integer.class), count);
		}
	};
	public AVCodecContext() {
		super();
	}
	public AVCodecContext(Pointer pointer) {
		super(pointer);
	}
}
