package org.ffmpeg.avdevice57;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import org.ffmpeg.avutil55.AVRational;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavdevice\avdevice.h:134</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVDeviceCapabilitiesQuery extends Structure {
	/** C type : const AVClass* */
	public Pointer av_class;
	/** C type : AVFormatContext* */
	public org.ffmpeg.avformat57.AVFormatContext.ByReference device_context;
	/**
	 * @see org.ffmpeg.avcodec57.Avcodec57Library#AVCodecID<br>
	 * C type : AVCodecID
	 */
	public int codec;
	/**
	 * @see org.ffmpeg.avutil55.Avutil55Library#AVSampleFormat<br>
	 * C type : AVSampleFormat
	 */
	public int sample_format;
	/**
	 * @see org.ffmpeg.avutil55.Avutil55Library#AVPixelFormat<br>
	 * C type : AVPixelFormat
	 */
	public int pixel_format;
	public int sample_rate;
	public int channels;
	public long channel_layout;
	public int window_width;
	public int window_height;
	public int frame_width;
	public int frame_height;
	/** C type : AVRational */
	public AVRational fps;
	public AVDeviceCapabilitiesQuery() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("av_class", "device_context", "codec", "sample_format", "pixel_format", "sample_rate", "channels", "channel_layout", "window_width", "window_height", "frame_width", "frame_height", "fps");
	}
	public AVDeviceCapabilitiesQuery(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVDeviceCapabilitiesQuery implements Structure.ByReference {
		
	};
	public static class ByValue extends AVDeviceCapabilitiesQuery implements Structure.ByValue {
		
	};
}
