package org.ffmpeg.avdevice57;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavdevice\avdevice.h:57</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVDeviceRect extends Structure {
	/** < x coordinate of top left corner */
	public int x;
	/** < y coordinate of top left corner */
	public int y;
	/** < width */
	public int width;
	/** < height */
	public int height;
	public AVDeviceRect() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("x", "y", "width", "height");
	}
	/**
	 * @param x < x coordinate of top left corner<br>
	 * @param y < y coordinate of top left corner<br>
	 * @param width < width<br>
	 * @param height < height
	 */
	public AVDeviceRect(int x, int y, int width, int height) {
		super();
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
	}
	public AVDeviceRect(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVDeviceRect implements Structure.ByReference {
		
	};
	public static class ByValue extends AVDeviceRect implements Structure.ByValue {
		
	};
}
