package org.ffmpeg.avcodec57;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : .\libavcodec\avcodec.h:2402</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVBitStreamFilter extends Structure {
	/** C type : const char* */
	public Pointer name;
	/** C type : AVCodecID* */
	public IntByReference codec_ids;
	/** C type : const AVClass* */
	public Pointer priv_class;
	public int priv_data_size;
	/** C type : init_callback* */
	public org.ffmpeg.avfilter6.AVFilter.init_callback init;
	/** C type : filter_callback* */
	public filter_callback filter;
	/** C type : close_callback* */
	public close_callback close;
	/** <i>native declaration : .\libavcodec\avcodec.h:2399</i> */
	public interface init_callback extends Callback {
		int apply(AVBSFContext ctx);
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:2400</i> */
	public interface filter_callback extends Callback {
		int apply(AVBSFContext ctx, AVPacket pkt);
	};
	/** <i>native declaration : .\libavcodec\avcodec.h:2401</i> */
	public interface close_callback extends Callback {
		void apply(AVBSFContext ctx);
	};
	public AVBitStreamFilter() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("name", "codec_ids", "priv_class", "priv_data_size", "init", "filter", "close");
	}
	/**
	 * @param name C type : const char*<br>
	 * @param codec_ids C type : AVCodecID*<br>
	 * @param priv_class C type : const AVClass*<br>
	 * @param init C type : init_callback*<br>
	 * @param filter C type : filter_callback*<br>
	 * @param close C type : close_callback*
	 */
	public AVBitStreamFilter(Pointer name, IntByReference codec_ids, Pointer priv_class, int priv_data_size, org.ffmpeg.avfilter6.AVFilter.init_callback init, filter_callback filter, close_callback close) {
		super();
		this.name = name;
		this.codec_ids = codec_ids;
		this.priv_class = priv_class;
		this.priv_data_size = priv_data_size;
		this.init = init;
		this.filter = filter;
		this.close = close;
	}
	public AVBitStreamFilter(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVBitStreamFilter implements Structure.ByReference {
		
	};
	public static class ByValue extends AVBitStreamFilter implements Structure.ByValue {
		
	};
}
