package org.ffmpeg.avcodec57;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : .\libavcodec\avcodec.h:1120</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVSubtitle extends Structure {
	/** 0 = graphics */
	public short format;
	/** relative to packet pts, in ms */
	public int start_display_time;
	/** relative to packet pts, in ms */
	public int end_display_time;
	public int num_rects;
	/** C type : AVSubtitleRect** */
	public org.ffmpeg.avcodec57.AVSubtitleRect.ByReference[] rects;
	/** < Same as packet pts, in AV_TIME_BASE */
	public long pts;
	public AVSubtitle() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("format", "start_display_time", "end_display_time", "num_rects", "rects", "pts");
	}
	/**
	 * @param format 0 = graphics<br>
	 * @param start_display_time relative to packet pts, in ms<br>
	 * @param end_display_time relative to packet pts, in ms<br>
	 * @param rects C type : AVSubtitleRect**<br>
	 * @param pts < Same as packet pts, in AV_TIME_BASE
	 */
	public AVSubtitle(short format, int start_display_time, int end_display_time, int num_rects, org.ffmpeg.avcodec57.AVSubtitleRect.ByReference rects[], long pts) {
		super();
		this.format = format;
		this.start_display_time = start_display_time;
		this.end_display_time = end_display_time;
		this.num_rects = num_rects;
		if ((rects.length != this.rects.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.rects = rects;
		this.pts = pts;
	}
	public AVSubtitle(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVSubtitle implements Structure.ByReference {
		
	};
	public static class ByValue extends AVSubtitle implements Structure.ByValue {
		
	};
}
