/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class charlie_laplacian_decoder_essential_FFmpegDecoder */

#ifndef _Included_charlie_laplacian_decoder_essential_FFmpegDecoder
#define _Included_charlie_laplacian_decoder_essential_FFmpegDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    seek
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_seek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    closeInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_closeInternal
  (JNIEnv *, jobject);

/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    playThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_playThread
  (JNIEnv *, jobject);

/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    startupNativeLibs
 * Signature: (FII)V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_startupNativeLibs
  (JNIEnv *, jobject, jfloat, jint, jint);

/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    initWithStream
 * Signature: (Lcharlie/laplacian/stream/TrackStream;)V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_initWithStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    initWithURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_initWithURL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     charlie_laplacian_decoder_essential_FFmpegDecoder
 * Method:    globalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_charlie_laplacian_decoder_essential_FFmpegDecoder_globalInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
