/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class charlie_laplacian_decoder_essential_FFmpegDecoder_Companion */

#ifndef _Included_charlie_laplacian_decoder_essential_FFmpegDecoder_Companion
#define _Included_charlie_laplacian_decoder_essential_FFmpegDecoder_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
