package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.util.DefaultParameterizedType;
import org.ffmpeg.avcodec.AVCodec;
import org.ffmpeg.avcodec.AVCodecLibrary.AVCodecID;
import org.ffmpeg.avformat.AVFormatLibrary.AVDurationEstimationMethod;
import org.ffmpeg.avformat.AVFormatLibrary.av_format_control_message;
import org.ffmpeg.avutil.AVClass;
import org.ffmpeg.avutil.AVDictionary;
/**
 * <i>native declaration : libavformat\avformat.h:442</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat-57") 
public class AVFormatContext extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : const AVClass* */
	@Field(0) 
	public Pointer<AVClass > av_class() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : const AVClass* */
	@Field(0) 
	public AVFormatContext av_class(Pointer<AVClass > av_class) {
		this.io.setPointerField(this, 0, av_class);
		return this;
	}
	/** C type : AVInputFormat* */
	@Field(1) 
	public Pointer<AVInputFormat > iformat() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : AVInputFormat* */
	@Field(1) 
	public AVFormatContext iformat(Pointer<AVInputFormat > iformat) {
		this.io.setPointerField(this, 1, iformat);
		return this;
	}
	/** C type : AVOutputFormat* */
	@Field(2) 
	public Pointer<AVOutputFormat > oformat() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : AVOutputFormat* */
	@Field(2) 
	public AVFormatContext oformat(Pointer<AVOutputFormat > oformat) {
		this.io.setPointerField(this, 2, oformat);
		return this;
	}
	/** C type : void* */
	@Field(3) 
	public Pointer<? > priv_data() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : void* */
	@Field(3) 
	public AVFormatContext priv_data(Pointer<? > priv_data) {
		this.io.setPointerField(this, 3, priv_data);
		return this;
	}
	/** C type : AVIOContext* */
	@Field(4) 
	public Pointer<AVIOContext > pb() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : AVIOContext* */
	@Field(4) 
	public AVFormatContext pb(Pointer<AVIOContext > pb) {
		this.io.setPointerField(this, 4, pb);
		return this;
	}
	@Field(5) 
	public int ctx_flags() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public AVFormatContext ctx_flags(int ctx_flags) {
		this.io.setIntField(this, 5, ctx_flags);
		return this;
	}
	@Field(6) 
	public int nb_streams() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public AVFormatContext nb_streams(int nb_streams) {
		this.io.setIntField(this, 6, nb_streams);
		return this;
	}
	/** C type : AVStream** */
	@Field(7) 
	public Pointer<Pointer<AVStream > > streams() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : AVStream** */
	@Field(7) 
	public AVFormatContext streams(Pointer<Pointer<AVStream > > streams) {
		this.io.setPointerField(this, 7, streams);
		return this;
	}
	/** C type : char[1024] */
	@Array({1024}) 
	@Field(8) 
	public Pointer<Byte > filename() {
		return this.io.getPointerField(this, 8);
	}
	@Field(9) 
	public long start_time() {
		return this.io.getLongField(this, 9);
	}
	@Field(9) 
	public AVFormatContext start_time(long start_time) {
		this.io.setLongField(this, 9, start_time);
		return this;
	}
	@Field(10) 
	public long duration() {
		return this.io.getLongField(this, 10);
	}
	@Field(10) 
	public AVFormatContext duration(long duration) {
		this.io.setLongField(this, 10, duration);
		return this;
	}
	@Field(11) 
	public long bit_rate() {
		return this.io.getLongField(this, 11);
	}
	@Field(11) 
	public AVFormatContext bit_rate(long bit_rate) {
		this.io.setLongField(this, 11, bit_rate);
		return this;
	}
	@Field(12) 
	public int packet_size() {
		return this.io.getIntField(this, 12);
	}
	@Field(12) 
	public AVFormatContext packet_size(int packet_size) {
		this.io.setIntField(this, 12, packet_size);
		return this;
	}
	@Field(13) 
	public int max_delay() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public AVFormatContext max_delay(int max_delay) {
		this.io.setIntField(this, 13, max_delay);
		return this;
	}
	@Field(14) 
	public int flags() {
		return this.io.getIntField(this, 14);
	}
	@Field(14) 
	public AVFormatContext flags(int flags) {
		this.io.setIntField(this, 14, flags);
		return this;
	}
	@Field(15) 
	public long probesize() {
		return this.io.getLongField(this, 15);
	}
	@Field(15) 
	public AVFormatContext probesize(long probesize) {
		this.io.setLongField(this, 15, probesize);
		return this;
	}
	@Field(16) 
	public long max_analyze_duration() {
		return this.io.getLongField(this, 16);
	}
	@Field(16) 
	public AVFormatContext max_analyze_duration(long max_analyze_duration) {
		this.io.setLongField(this, 16, max_analyze_duration);
		return this;
	}
	/** C type : const uint8_t* */
	@Field(17) 
	public Pointer<Byte > key() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : const uint8_t* */
	@Field(17) 
	public AVFormatContext key(Pointer<Byte > key) {
		this.io.setPointerField(this, 17, key);
		return this;
	}
	@Field(18) 
	public int keylen() {
		return this.io.getIntField(this, 18);
	}
	@Field(18) 
	public AVFormatContext keylen(int keylen) {
		this.io.setIntField(this, 18, keylen);
		return this;
	}
	@Field(19) 
	public int nb_programs() {
		return this.io.getIntField(this, 19);
	}
	@Field(19) 
	public AVFormatContext nb_programs(int nb_programs) {
		this.io.setIntField(this, 19, nb_programs);
		return this;
	}
	/** C type : AVProgram** */
	@Field(20) 
	public Pointer<Pointer<AVProgram > > programs() {
		return this.io.getPointerField(this, 20);
	}
	/** C type : AVProgram** */
	@Field(20) 
	public AVFormatContext programs(Pointer<Pointer<AVProgram > > programs) {
		this.io.setPointerField(this, 20, programs);
		return this;
	}
	/** C type : AVCodecID */
	@Field(21) 
	public IntValuedEnum<AVCodecID > video_codec_id() {
		return this.io.getEnumField(this, 21);
	}
	/** C type : AVCodecID */
	@Field(21) 
	public AVFormatContext video_codec_id(IntValuedEnum<AVCodecID > video_codec_id) {
		this.io.setEnumField(this, 21, video_codec_id);
		return this;
	}
	/** C type : AVCodecID */
	@Field(22) 
	public IntValuedEnum<AVCodecID > audio_codec_id() {
		return this.io.getEnumField(this, 22);
	}
	/** C type : AVCodecID */
	@Field(22) 
	public AVFormatContext audio_codec_id(IntValuedEnum<AVCodecID > audio_codec_id) {
		this.io.setEnumField(this, 22, audio_codec_id);
		return this;
	}
	/** C type : AVCodecID */
	@Field(23) 
	public IntValuedEnum<AVCodecID > subtitle_codec_id() {
		return this.io.getEnumField(this, 23);
	}
	/** C type : AVCodecID */
	@Field(23) 
	public AVFormatContext subtitle_codec_id(IntValuedEnum<AVCodecID > subtitle_codec_id) {
		this.io.setEnumField(this, 23, subtitle_codec_id);
		return this;
	}
	@Field(24) 
	public int max_index_size() {
		return this.io.getIntField(this, 24);
	}
	@Field(24) 
	public AVFormatContext max_index_size(int max_index_size) {
		this.io.setIntField(this, 24, max_index_size);
		return this;
	}
	@Field(25) 
	public int max_picture_buffer() {
		return this.io.getIntField(this, 25);
	}
	@Field(25) 
	public AVFormatContext max_picture_buffer(int max_picture_buffer) {
		this.io.setIntField(this, 25, max_picture_buffer);
		return this;
	}
	@Field(26) 
	public int nb_chapters() {
		return this.io.getIntField(this, 26);
	}
	@Field(26) 
	public AVFormatContext nb_chapters(int nb_chapters) {
		this.io.setIntField(this, 26, nb_chapters);
		return this;
	}
	/** C type : AVChapter** */
	@Field(27) 
	public Pointer<Pointer<AVChapter > > chapters() {
		return this.io.getPointerField(this, 27);
	}
	/** C type : AVChapter** */
	@Field(27) 
	public AVFormatContext chapters(Pointer<Pointer<AVChapter > > chapters) {
		this.io.setPointerField(this, 27, chapters);
		return this;
	}
	/** C type : AVDictionary* */
	@Field(28) 
	public Pointer<AVDictionary > metadata() {
		return this.io.getPointerField(this, 28);
	}
	/** C type : AVDictionary* */
	@Field(28) 
	public AVFormatContext metadata(Pointer<AVDictionary > metadata) {
		this.io.setPointerField(this, 28, metadata);
		return this;
	}
	@Field(29) 
	public long start_time_realtime() {
		return this.io.getLongField(this, 29);
	}
	@Field(29) 
	public AVFormatContext start_time_realtime(long start_time_realtime) {
		this.io.setLongField(this, 29, start_time_realtime);
		return this;
	}
	@Field(30) 
	public int fps_probe_size() {
		return this.io.getIntField(this, 30);
	}
	@Field(30) 
	public AVFormatContext fps_probe_size(int fps_probe_size) {
		this.io.setIntField(this, 30, fps_probe_size);
		return this;
	}
	@Field(31) 
	public int error_recognition() {
		return this.io.getIntField(this, 31);
	}
	@Field(31) 
	public AVFormatContext error_recognition(int error_recognition) {
		this.io.setIntField(this, 31, error_recognition);
		return this;
	}
	/** C type : AVIOInterruptCB */
	@Field(32) 
	public AVIOInterruptCB interrupt_callback() {
		return this.io.getNativeObjectField(this, 32);
	}
	/** C type : AVIOInterruptCB */
	@Field(32) 
	public AVFormatContext interrupt_callback(AVIOInterruptCB interrupt_callback) {
		this.io.setNativeObjectField(this, 32, interrupt_callback);
		return this;
	}
	@Field(33) 
	public int debug() {
		return this.io.getIntField(this, 33);
	}
	@Field(33) 
	public AVFormatContext debug(int debug) {
		this.io.setIntField(this, 33, debug);
		return this;
	}
	@Field(34) 
	public long max_interleave_delta() {
		return this.io.getLongField(this, 34);
	}
	@Field(34) 
	public AVFormatContext max_interleave_delta(long max_interleave_delta) {
		this.io.setLongField(this, 34, max_interleave_delta);
		return this;
	}
	@Field(35) 
	public int strict_std_compliance() {
		return this.io.getIntField(this, 35);
	}
	@Field(35) 
	public AVFormatContext strict_std_compliance(int strict_std_compliance) {
		this.io.setIntField(this, 35, strict_std_compliance);
		return this;
	}
	@Field(36) 
	public int event_flags() {
		return this.io.getIntField(this, 36);
	}
	@Field(36) 
	public AVFormatContext event_flags(int event_flags) {
		this.io.setIntField(this, 36, event_flags);
		return this;
	}
	@Field(37) 
	public int max_ts_probe() {
		return this.io.getIntField(this, 37);
	}
	@Field(37) 
	public AVFormatContext max_ts_probe(int max_ts_probe) {
		this.io.setIntField(this, 37, max_ts_probe);
		return this;
	}
	@Field(38) 
	public int avoid_negative_ts() {
		return this.io.getIntField(this, 38);
	}
	@Field(38) 
	public AVFormatContext avoid_negative_ts(int avoid_negative_ts) {
		this.io.setIntField(this, 38, avoid_negative_ts);
		return this;
	}
	@Field(39) 
	public int ts_id() {
		return this.io.getIntField(this, 39);
	}
	@Field(39) 
	public AVFormatContext ts_id(int ts_id) {
		this.io.setIntField(this, 39, ts_id);
		return this;
	}
	@Field(40) 
	public int audio_preload() {
		return this.io.getIntField(this, 40);
	}
	@Field(40) 
	public AVFormatContext audio_preload(int audio_preload) {
		this.io.setIntField(this, 40, audio_preload);
		return this;
	}
	@Field(41) 
	public int max_chunk_duration() {
		return this.io.getIntField(this, 41);
	}
	@Field(41) 
	public AVFormatContext max_chunk_duration(int max_chunk_duration) {
		this.io.setIntField(this, 41, max_chunk_duration);
		return this;
	}
	@Field(42) 
	public int max_chunk_size() {
		return this.io.getIntField(this, 42);
	}
	@Field(42) 
	public AVFormatContext max_chunk_size(int max_chunk_size) {
		this.io.setIntField(this, 42, max_chunk_size);
		return this;
	}
	@Field(43) 
	public int use_wallclock_as_timestamps() {
		return this.io.getIntField(this, 43);
	}
	@Field(43) 
	public AVFormatContext use_wallclock_as_timestamps(int use_wallclock_as_timestamps) {
		this.io.setIntField(this, 43, use_wallclock_as_timestamps);
		return this;
	}
	@Field(44) 
	public int avio_flags() {
		return this.io.getIntField(this, 44);
	}
	@Field(44) 
	public AVFormatContext avio_flags(int avio_flags) {
		this.io.setIntField(this, 44, avio_flags);
		return this;
	}
	/** C type : AVDurationEstimationMethod */
	@Field(45) 
	public IntValuedEnum<AVDurationEstimationMethod > duration_estimation_method() {
		return this.io.getEnumField(this, 45);
	}
	/** C type : AVDurationEstimationMethod */
	@Field(45) 
	public AVFormatContext duration_estimation_method(IntValuedEnum<AVDurationEstimationMethod > duration_estimation_method) {
		this.io.setEnumField(this, 45, duration_estimation_method);
		return this;
	}
	@Field(46) 
	public long skip_initial_bytes() {
		return this.io.getLongField(this, 46);
	}
	@Field(46) 
	public AVFormatContext skip_initial_bytes(long skip_initial_bytes) {
		this.io.setLongField(this, 46, skip_initial_bytes);
		return this;
	}
	@Field(47) 
	public int correct_ts_overflow() {
		return this.io.getIntField(this, 47);
	}
	@Field(47) 
	public AVFormatContext correct_ts_overflow(int correct_ts_overflow) {
		this.io.setIntField(this, 47, correct_ts_overflow);
		return this;
	}
	@Field(48) 
	public int seek2any() {
		return this.io.getIntField(this, 48);
	}
	@Field(48) 
	public AVFormatContext seek2any(int seek2any) {
		this.io.setIntField(this, 48, seek2any);
		return this;
	}
	@Field(49) 
	public int flush_packets() {
		return this.io.getIntField(this, 49);
	}
	@Field(49) 
	public AVFormatContext flush_packets(int flush_packets) {
		this.io.setIntField(this, 49, flush_packets);
		return this;
	}
	@Field(50) 
	public int probe_score() {
		return this.io.getIntField(this, 50);
	}
	@Field(50) 
	public AVFormatContext probe_score(int probe_score) {
		this.io.setIntField(this, 50, probe_score);
		return this;
	}
	@Field(51) 
	public int format_probesize() {
		return this.io.getIntField(this, 51);
	}
	@Field(51) 
	public AVFormatContext format_probesize(int format_probesize) {
		this.io.setIntField(this, 51, format_probesize);
		return this;
	}
	/** C type : char* */
	@Field(52) 
	public Pointer<Byte > codec_whitelist() {
		return this.io.getPointerField(this, 52);
	}
	/** C type : char* */
	@Field(52) 
	public AVFormatContext codec_whitelist(Pointer<Byte > codec_whitelist) {
		this.io.setPointerField(this, 52, codec_whitelist);
		return this;
	}
	/** C type : char* */
	@Field(53) 
	public Pointer<Byte > format_whitelist() {
		return this.io.getPointerField(this, 53);
	}
	/** C type : char* */
	@Field(53) 
	public AVFormatContext format_whitelist(Pointer<Byte > format_whitelist) {
		this.io.setPointerField(this, 53, format_whitelist);
		return this;
	}
	/** C type : AVFormatInternal* */
	@Field(54) 
	public Pointer<AVFormatInternal > internal() {
		return this.io.getPointerField(this, 54);
	}
	/** C type : AVFormatInternal* */
	@Field(54) 
	public AVFormatContext internal(Pointer<AVFormatInternal > internal) {
		this.io.setPointerField(this, 54, internal);
		return this;
	}
	@Field(55) 
	public int io_repositioned() {
		return this.io.getIntField(this, 55);
	}
	@Field(55) 
	public AVFormatContext io_repositioned(int io_repositioned) {
		this.io.setIntField(this, 55, io_repositioned);
		return this;
	}
	/** C type : AVCodec* */
	@Field(56) 
	public Pointer<AVCodec > video_codec() {
		return this.io.getPointerField(this, 56);
	}
	/** C type : AVCodec* */
	@Field(56) 
	public AVFormatContext video_codec(Pointer<AVCodec > video_codec) {
		this.io.setPointerField(this, 56, video_codec);
		return this;
	}
	/** C type : AVCodec* */
	@Field(57) 
	public Pointer<AVCodec > audio_codec() {
		return this.io.getPointerField(this, 57);
	}
	/** C type : AVCodec* */
	@Field(57) 
	public AVFormatContext audio_codec(Pointer<AVCodec > audio_codec) {
		this.io.setPointerField(this, 57, audio_codec);
		return this;
	}
	/** C type : AVCodec* */
	@Field(58) 
	public Pointer<AVCodec > subtitle_codec() {
		return this.io.getPointerField(this, 58);
	}
	/** C type : AVCodec* */
	@Field(58) 
	public AVFormatContext subtitle_codec(Pointer<AVCodec > subtitle_codec) {
		this.io.setPointerField(this, 58, subtitle_codec);
		return this;
	}
	/** C type : AVCodec* */
	@Field(59) 
	public Pointer<AVCodec > data_codec() {
		return this.io.getPointerField(this, 59);
	}
	/** C type : AVCodec* */
	@Field(59) 
	public AVFormatContext data_codec(Pointer<AVCodec > data_codec) {
		this.io.setPointerField(this, 59, data_codec);
		return this;
	}
	@Field(60) 
	public int metadata_header_padding() {
		return this.io.getIntField(this, 60);
	}
	@Field(60) 
	public AVFormatContext metadata_header_padding(int metadata_header_padding) {
		this.io.setIntField(this, 60, metadata_header_padding);
		return this;
	}
	/** C type : void* */
	@Field(61) 
	public Pointer<? > opaque() {
		return this.io.getPointerField(this, 61);
	}
	/** C type : void* */
	@Field(61) 
	public AVFormatContext opaque(Pointer<? > opaque) {
		this.io.setPointerField(this, 61, opaque);
		return this;
	}
	/** C type : av_format_control_message */
	@Field(62) 
	public Pointer<av_format_control_message > control_message_cb() {
		return this.io.getPointerField(this, 62);
	}
	/** C type : av_format_control_message */
	@Field(62) 
	public AVFormatContext control_message_cb(Pointer<av_format_control_message > control_message_cb) {
		this.io.setPointerField(this, 62, control_message_cb);
		return this;
	}
	@Field(63) 
	public long output_ts_offset() {
		return this.io.getLongField(this, 63);
	}
	@Field(63) 
	public AVFormatContext output_ts_offset(long output_ts_offset) {
		this.io.setLongField(this, 63, output_ts_offset);
		return this;
	}
	/** C type : uint8_t* */
	@Field(64) 
	public Pointer<Byte > dump_separator() {
		return this.io.getPointerField(this, 64);
	}
	/** C type : uint8_t* */
	@Field(64) 
	public AVFormatContext dump_separator(Pointer<Byte > dump_separator) {
		this.io.setPointerField(this, 64, dump_separator);
		return this;
	}
	/** C type : AVCodecID */
	@Field(65) 
	public IntValuedEnum<AVCodecID > data_codec_id() {
		return this.io.getEnumField(this, 65);
	}
	/** C type : AVCodecID */
	@Field(65) 
	public AVFormatContext data_codec_id(IntValuedEnum<AVCodecID > data_codec_id) {
		this.io.setEnumField(this, 65, data_codec_id);
		return this;
	}
	/** C type : open_cb_callback* */
	@Field(66) 
	public Pointer<open_cb_callback > open_cb() {
		return this.io.getPointerField(this, 66);
	}
	/** C type : open_cb_callback* */
	@Field(66) 
	public AVFormatContext open_cb(Pointer<open_cb_callback > open_cb) {
		this.io.setPointerField(this, 66, open_cb);
		return this;
	}
	/** C type : char* */
	@Field(67) 
	public Pointer<Byte > protocol_whitelist() {
		return this.io.getPointerField(this, 67);
	}
	/** C type : char* */
	@Field(67) 
	public AVFormatContext protocol_whitelist(Pointer<Byte > protocol_whitelist) {
		this.io.setPointerField(this, 67, protocol_whitelist);
		return this;
	}
	/** C type : io_open_callback* */
	@Field(68) 
	public Pointer<io_open_callback > io_open() {
		return this.io.getPointerField(this, 68);
	}
	/** C type : io_open_callback* */
	@Field(68) 
	public AVFormatContext io_open(Pointer<io_open_callback > io_open) {
		this.io.setPointerField(this, 68, io_open);
		return this;
	}
	/** C type : io_close_callback* */
	@Field(69) 
	public Pointer<io_close_callback > io_close() {
		return this.io.getPointerField(this, 69);
	}
	/** C type : io_close_callback* */
	@Field(69) 
	public AVFormatContext io_close(Pointer<io_close_callback > io_close) {
		this.io.setPointerField(this, 69, io_close);
		return this;
	}
	/** C type : char* */
	@Field(70) 
	public Pointer<Byte > protocol_blacklist() {
		return this.io.getPointerField(this, 70);
	}
	/** C type : char* */
	@Field(70) 
	public AVFormatContext protocol_blacklist(Pointer<Byte > protocol_blacklist) {
		this.io.setPointerField(this, 70, protocol_blacklist);
		return this;
	}
	@Field(71) 
	public int max_streams() {
		return this.io.getIntField(this, 71);
	}
	@Field(71) 
	public AVFormatContext max_streams(int max_streams) {
		this.io.setIntField(this, 71, max_streams);
		return this;
	}
	/** <i>native declaration : libavformat\avformat.h:439</i> */
	public static abstract class open_cb_callback extends Callback<open_cb_callback > {
		public int apply(Pointer<AVFormatContext > s, Pointer<Pointer<AVIOContext > > p, Pointer<Byte > url, int flags, Pointer<AVIOInterruptCB > int_cb, Pointer<Pointer<AVDictionary > > options) {
			return apply(Pointer.getPeer(s), Pointer.getPeer(p), Pointer.getPeer(url), flags, Pointer.getPeer(int_cb), Pointer.getPeer(options));
		}
		public int apply(@Ptr long s, @Ptr long p, @Ptr long url, int flags, @Ptr long int_cb, @Ptr long options) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(p, DefaultParameterizedType.paramType(Pointer.class, AVIOContext.class)), (Pointer)Pointer.pointerToAddress(url, Byte.class), flags, (Pointer)Pointer.pointerToAddress(int_cb, AVIOInterruptCB.class), (Pointer)Pointer.pointerToAddress(options, DefaultParameterizedType.paramType(Pointer.class, AVDictionary.class)));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:440</i> */
	public static abstract class io_open_callback extends Callback<io_open_callback > {
		public int apply(Pointer<AVFormatContext > s, Pointer<Pointer<AVIOContext > > pb, Pointer<Byte > url, int flags, Pointer<Pointer<AVDictionary > > options) {
			return apply(Pointer.getPeer(s), Pointer.getPeer(pb), Pointer.getPeer(url), flags, Pointer.getPeer(options));
		}
		public int apply(@Ptr long s, @Ptr long pb, @Ptr long url, int flags, @Ptr long options) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(pb, DefaultParameterizedType.paramType(Pointer.class, AVIOContext.class)), (Pointer)Pointer.pointerToAddress(url, Byte.class), flags, (Pointer)Pointer.pointerToAddress(options, DefaultParameterizedType.paramType(Pointer.class, AVDictionary.class)));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:441</i> */
	public static abstract class io_close_callback extends Callback<io_close_callback > {
		public void apply(Pointer<AVFormatContext > s, Pointer<AVIOContext > pb) {
			apply(Pointer.getPeer(s), Pointer.getPeer(pb));
		}
		public void apply(@Ptr long s, @Ptr long pb) {
			apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(pb, AVIOContext.class));
		}
	};
	public AVFormatContext() {
		super();
	}
	public AVFormatContext(Pointer pointer) {
		super(pointer);
	}
}
