package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.ffmpeg.avcodec.AVPacket;
import org.ffmpeg.avdevice.AVDeviceCapabilitiesQuery;
import org.ffmpeg.avdevice.AVDeviceInfoList;
import org.ffmpeg.avutil.AVClass;
/**
 * <i>native declaration : libavformat\avformat.h:149</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat-57") 
public class AVInputFormat extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : const char* */
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : const char* */
	@Field(0) 
	public AVInputFormat name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/** C type : const char* */
	@Field(1) 
	public Pointer<Byte > long_name() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : const char* */
	@Field(1) 
	public AVInputFormat long_name(Pointer<Byte > long_name) {
		this.io.setPointerField(this, 1, long_name);
		return this;
	}
	@Field(2) 
	public int flags() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public AVInputFormat flags(int flags) {
		this.io.setIntField(this, 2, flags);
		return this;
	}
	/** C type : const char* */
	@Field(3) 
	public Pointer<Byte > extensions() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : const char* */
	@Field(3) 
	public AVInputFormat extensions(Pointer<Byte > extensions) {
		this.io.setPointerField(this, 3, extensions);
		return this;
	}
	/** C type : AVCodecTag** */
	@Field(4) 
	public Pointer<Pointer<AVCodecTag > > codec_tag() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : AVCodecTag** */
	@Field(4) 
	public AVInputFormat codec_tag(Pointer<Pointer<AVCodecTag > > codec_tag) {
		this.io.setPointerField(this, 4, codec_tag);
		return this;
	}
	/**
	 * < AVClass for the private context<br>
	 * C type : const AVClass*
	 */
	@Field(5) 
	public Pointer<AVClass > priv_class() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * < AVClass for the private context<br>
	 * C type : const AVClass*
	 */
	@Field(5) 
	public AVInputFormat priv_class(Pointer<AVClass > priv_class) {
		this.io.setPointerField(this, 5, priv_class);
		return this;
	}
	/** C type : const char* */
	@Field(6) 
	public Pointer<Byte > mime_type() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : const char* */
	@Field(6) 
	public AVInputFormat mime_type(Pointer<Byte > mime_type) {
		this.io.setPointerField(this, 6, mime_type);
		return this;
	}
	/** C type : AVInputFormat* */
	@Field(7) 
	public Pointer<AVInputFormat > next() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : AVInputFormat* */
	@Field(7) 
	public AVInputFormat next(Pointer<AVInputFormat > next) {
		this.io.setPointerField(this, 7, next);
		return this;
	}
	@Field(8) 
	public int raw_codec_id() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public AVInputFormat raw_codec_id(int raw_codec_id) {
		this.io.setIntField(this, 8, raw_codec_id);
		return this;
	}
	@Field(9) 
	public int priv_data_size() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public AVInputFormat priv_data_size(int priv_data_size) {
		this.io.setIntField(this, 9, priv_data_size);
		return this;
	}
	/** C type : read_probe_callback* */
	@Field(10) 
	public Pointer<read_probe_callback > read_probe() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : read_probe_callback* */
	@Field(10) 
	public AVInputFormat read_probe(Pointer<read_probe_callback > read_probe) {
		this.io.setPointerField(this, 10, read_probe);
		return this;
	}
	/** C type : read_header_callback* */
	@Field(11) 
	public Pointer<read_header_callback > read_header() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : read_header_callback* */
	@Field(11) 
	public AVInputFormat read_header(Pointer<read_header_callback > read_header) {
		this.io.setPointerField(this, 11, read_header);
		return this;
	}
	/** C type : read_packet_callback* */
	@Field(12) 
	public Pointer<read_packet_callback > read_packet() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : read_packet_callback* */
	@Field(12) 
	public AVInputFormat read_packet(Pointer<read_packet_callback > read_packet) {
		this.io.setPointerField(this, 12, read_packet);
		return this;
	}
	/** C type : read_close_callback* */
	@Field(13) 
	public Pointer<read_close_callback > read_close() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : read_close_callback* */
	@Field(13) 
	public AVInputFormat read_close(Pointer<read_close_callback > read_close) {
		this.io.setPointerField(this, 13, read_close);
		return this;
	}
	/** C type : read_seek_callback* */
	@Field(14) 
	public Pointer<read_seek_callback > read_seek() {
		return this.io.getPointerField(this, 14);
	}
	/** C type : read_seek_callback* */
	@Field(14) 
	public AVInputFormat read_seek(Pointer<read_seek_callback > read_seek) {
		this.io.setPointerField(this, 14, read_seek);
		return this;
	}
	/** C type : read_timestamp_callback* */
	@Field(15) 
	public Pointer<read_timestamp_callback > read_timestamp() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : read_timestamp_callback* */
	@Field(15) 
	public AVInputFormat read_timestamp(Pointer<read_timestamp_callback > read_timestamp) {
		this.io.setPointerField(this, 15, read_timestamp);
		return this;
	}
	/** C type : read_play_callback* */
	@Field(16) 
	public Pointer<read_play_callback > read_play() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : read_play_callback* */
	@Field(16) 
	public AVInputFormat read_play(Pointer<read_play_callback > read_play) {
		this.io.setPointerField(this, 16, read_play);
		return this;
	}
	/** C type : read_pause_callback* */
	@Field(17) 
	public Pointer<read_pause_callback > read_pause() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : read_pause_callback* */
	@Field(17) 
	public AVInputFormat read_pause(Pointer<read_pause_callback > read_pause) {
		this.io.setPointerField(this, 17, read_pause);
		return this;
	}
	/** C type : read_seek2_callback* */
	@Field(18) 
	public Pointer<read_seek2_callback > read_seek2() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : read_seek2_callback* */
	@Field(18) 
	public AVInputFormat read_seek2(Pointer<read_seek2_callback > read_seek2) {
		this.io.setPointerField(this, 18, read_seek2);
		return this;
	}
	/** C type : get_device_list_callback* */
	@Field(19) 
	public Pointer<get_device_list_callback > get_device_list() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : get_device_list_callback* */
	@Field(19) 
	public AVInputFormat get_device_list(Pointer<get_device_list_callback > get_device_list) {
		this.io.setPointerField(this, 19, get_device_list);
		return this;
	}
	/** C type : create_device_capabilities_callback* */
	@Field(20) 
	public Pointer<create_device_capabilities_callback > create_device_capabilities() {
		return this.io.getPointerField(this, 20);
	}
	/** C type : create_device_capabilities_callback* */
	@Field(20) 
	public AVInputFormat create_device_capabilities(Pointer<create_device_capabilities_callback > create_device_capabilities) {
		this.io.setPointerField(this, 20, create_device_capabilities);
		return this;
	}
	/** C type : free_device_capabilities_callback* */
	@Field(21) 
	public Pointer<free_device_capabilities_callback > free_device_capabilities() {
		return this.io.getPointerField(this, 21);
	}
	/** C type : free_device_capabilities_callback* */
	@Field(21) 
	public AVInputFormat free_device_capabilities(Pointer<free_device_capabilities_callback > free_device_capabilities) {
		this.io.setPointerField(this, 21, free_device_capabilities);
		return this;
	}
	/** <i>native declaration : libavformat\avformat.h:137</i> */
	public static abstract class read_probe_callback extends Callback<read_probe_callback > {
		public int apply(Pointer<AVProbeData > AVProbeDataPtr1) {
			return apply(Pointer.getPeer(AVProbeDataPtr1));
		}
		public int apply(@Ptr long AVProbeDataPtr1) {
			return apply((Pointer)Pointer.pointerToAddress(AVProbeDataPtr1, AVProbeData.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:138</i> */
	public static abstract class read_header_callback extends Callback<read_header_callback > {
		public int apply(Pointer<AVFormatContext > AVFormatContextPtr1) {
			return apply(Pointer.getPeer(AVFormatContextPtr1));
		}
		public int apply(@Ptr long AVFormatContextPtr1) {
			return apply((Pointer)Pointer.pointerToAddress(AVFormatContextPtr1, AVFormatContext.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:139</i> */
	public static abstract class read_packet_callback extends Callback<read_packet_callback > {
		public int apply(Pointer<AVFormatContext > AVFormatContextPtr1, Pointer<AVPacket > pkt) {
			return apply(Pointer.getPeer(AVFormatContextPtr1), Pointer.getPeer(pkt));
		}
		public int apply(@Ptr long AVFormatContextPtr1, @Ptr long pkt) {
			return apply((Pointer)Pointer.pointerToAddress(AVFormatContextPtr1, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(pkt, AVPacket.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:140</i> */
	public static abstract class read_close_callback extends Callback<read_close_callback > {
		public int apply(Pointer<AVFormatContext > AVFormatContextPtr1) {
			return apply(Pointer.getPeer(AVFormatContextPtr1));
		}
		public int apply(@Ptr long AVFormatContextPtr1) {
			return apply((Pointer)Pointer.pointerToAddress(AVFormatContextPtr1, AVFormatContext.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:141</i> */
	public static abstract class read_seek_callback extends Callback<read_seek_callback > {
		public int apply(Pointer<AVFormatContext > AVFormatContextPtr1, int stream_index, long timestamp, int flags) {
			return apply(Pointer.getPeer(AVFormatContextPtr1), stream_index, timestamp, flags);
		}
		public int apply(@Ptr long AVFormatContextPtr1, int stream_index, long timestamp, int flags) {
			return apply((Pointer)Pointer.pointerToAddress(AVFormatContextPtr1, AVFormatContext.class), stream_index, timestamp, flags);
		}
	};
	/** <i>native declaration : libavformat\avformat.h:142</i> */
	public static abstract class read_timestamp_callback extends Callback<read_timestamp_callback > {
		public long apply(Pointer<AVFormatContext > s, int stream_index, Pointer<Long > pos, long pos_limit) {
			return apply(Pointer.getPeer(s), stream_index, Pointer.getPeer(pos), pos_limit);
		}
		public long apply(@Ptr long s, int stream_index, @Ptr long pos, long pos_limit) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), stream_index, (Pointer)Pointer.pointerToAddress(pos, Long.class), pos_limit);
		}
	};
	/** <i>native declaration : libavformat\avformat.h:143</i> */
	public static abstract class read_play_callback extends Callback<read_play_callback > {
		public int apply(Pointer<AVFormatContext > AVFormatContextPtr1) {
			return apply(Pointer.getPeer(AVFormatContextPtr1));
		}
		public int apply(@Ptr long AVFormatContextPtr1) {
			return apply((Pointer)Pointer.pointerToAddress(AVFormatContextPtr1, AVFormatContext.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:144</i> */
	public static abstract class read_pause_callback extends Callback<read_pause_callback > {
		public int apply(Pointer<AVFormatContext > AVFormatContextPtr1) {
			return apply(Pointer.getPeer(AVFormatContextPtr1));
		}
		public int apply(@Ptr long AVFormatContextPtr1) {
			return apply((Pointer)Pointer.pointerToAddress(AVFormatContextPtr1, AVFormatContext.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:145</i> */
	public static abstract class read_seek2_callback extends Callback<read_seek2_callback > {
		public int apply(Pointer<AVFormatContext > s, int stream_index, long min_ts, long ts, long max_ts, int flags) {
			return apply(Pointer.getPeer(s), stream_index, min_ts, ts, max_ts, flags);
		}
		public int apply(@Ptr long s, int stream_index, long min_ts, long ts, long max_ts, int flags) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), stream_index, min_ts, ts, max_ts, flags);
		}
	};
	/** <i>native declaration : libavformat\avformat.h:146</i> */
	public static abstract class get_device_list_callback extends Callback<get_device_list_callback > {
		public int apply(Pointer<AVFormatContext > s, Pointer<AVDeviceInfoList > device_list) {
			return apply(Pointer.getPeer(s), Pointer.getPeer(device_list));
		}
		public int apply(@Ptr long s, @Ptr long device_list) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(device_list, AVDeviceInfoList.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:147</i> */
	public static abstract class create_device_capabilities_callback extends Callback<create_device_capabilities_callback > {
		public int apply(Pointer<AVFormatContext > s, Pointer<AVDeviceCapabilitiesQuery > caps) {
			return apply(Pointer.getPeer(s), Pointer.getPeer(caps));
		}
		public int apply(@Ptr long s, @Ptr long caps) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(caps, AVDeviceCapabilitiesQuery.class));
		}
	};
	/** <i>native declaration : libavformat\avformat.h:148</i> */
	public static abstract class free_device_capabilities_callback extends Callback<free_device_capabilities_callback > {
		public int apply(Pointer<AVFormatContext > s, Pointer<AVDeviceCapabilitiesQuery > caps) {
			return apply(Pointer.getPeer(s), Pointer.getPeer(caps));
		}
		public int apply(@Ptr long s, @Ptr long caps) {
			return apply((Pointer)Pointer.pointerToAddress(s, AVFormatContext.class), (Pointer)Pointer.pointerToAddress(caps, AVDeviceCapabilitiesQuery.class));
		}
	};
	public AVInputFormat() {
		super();
	}
	public AVInputFormat(Pointer pointer) {
		super(pointer);
	}
}
