package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.ffmpeg.avcodec.AVCodecContext;
import org.ffmpeg.avcodec.AVCodecParameters;
import org.ffmpeg.avcodec.AVCodecParserContext;
import org.ffmpeg.avcodec.AVPacket;
import org.ffmpeg.avcodec.AVPacketSideData;
import org.ffmpeg.avcodec.AVCodecLibrary.AVDiscard;
import org.ffmpeg.avformat.AVFormatLibrary.AVStreamParseType;
import org.ffmpeg.avutil.AVDictionary;
import org.ffmpeg.avutil.AVRational;
/**
 * <i>native declaration : libavformat\avformat.h:271</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat-57") 
public class AVStream extends StructObject {
	static {
		BridJ.register();
	}
	/** < stream index in AVFormatContext */
	@Field(0) 
	public int index() {
		return this.io.getIntField(this, 0);
	}
	/** < stream index in AVFormatContext */
	@Field(0) 
	public AVStream index(int index) {
		this.io.setIntField(this, 0, index);
		return this;
	}
	@Field(1) 
	public int id() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public AVStream id(int id) {
		this.io.setIntField(this, 1, id);
		return this;
	}
	/** C type : AVCodecContext* */
	@Field(2) 
	public Pointer<AVCodecContext > codec() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : AVCodecContext* */
	@Field(2) 
	public AVStream codec(Pointer<AVCodecContext > codec) {
		this.io.setPointerField(this, 2, codec);
		return this;
	}
	/** C type : void* */
	@Field(3) 
	public Pointer<? > priv_data() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : void* */
	@Field(3) 
	public AVStream priv_data(Pointer<? > priv_data) {
		this.io.setPointerField(this, 3, priv_data);
		return this;
	}
	/** C type : AVFrac */
	@Field(4) 
	public AVFrac pts() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : AVFrac */
	@Field(4) 
	public AVStream pts(AVFrac pts) {
		this.io.setNativeObjectField(this, 4, pts);
		return this;
	}
	/** C type : AVRational */
	@Field(5) 
	public AVRational time_base() {
		return this.io.getNativeObjectField(this, 5);
	}
	/** C type : AVRational */
	@Field(5) 
	public AVStream time_base(AVRational time_base) {
		this.io.setNativeObjectField(this, 5, time_base);
		return this;
	}
	@Field(6) 
	public long start_time() {
		return this.io.getLongField(this, 6);
	}
	@Field(6) 
	public AVStream start_time(long start_time) {
		this.io.setLongField(this, 6, start_time);
		return this;
	}
	@Field(7) 
	public long duration() {
		return this.io.getLongField(this, 7);
	}
	@Field(7) 
	public AVStream duration(long duration) {
		this.io.setLongField(this, 7, duration);
		return this;
	}
	/** < number of frames in this stream if known or 0 */
	@Field(8) 
	public long nb_frames() {
		return this.io.getLongField(this, 8);
	}
	/** < number of frames in this stream if known or 0 */
	@Field(8) 
	public AVStream nb_frames(long nb_frames) {
		this.io.setLongField(this, 8, nb_frames);
		return this;
	}
	/** < AV_DISPOSITION_* bit field */
	@Field(9) 
	public int disposition() {
		return this.io.getIntField(this, 9);
	}
	/** < AV_DISPOSITION_* bit field */
	@Field(9) 
	public AVStream disposition(int disposition) {
		this.io.setIntField(this, 9, disposition);
		return this;
	}
	/**
	 * < Selects which packets can be discarded at will and do not need to be demuxed.<br>
	 * C type : AVDiscard
	 */
	@Field(10) 
	public IntValuedEnum<AVDiscard > discard() {
		return this.io.getEnumField(this, 10);
	}
	/**
	 * < Selects which packets can be discarded at will and do not need to be demuxed.<br>
	 * C type : AVDiscard
	 */
	@Field(10) 
	public AVStream discard(IntValuedEnum<AVDiscard > discard) {
		this.io.setEnumField(this, 10, discard);
		return this;
	}
	/** C type : AVRational */
	@Field(11) 
	public AVRational sample_aspect_ratio() {
		return this.io.getNativeObjectField(this, 11);
	}
	/** C type : AVRational */
	@Field(11) 
	public AVStream sample_aspect_ratio(AVRational sample_aspect_ratio) {
		this.io.setNativeObjectField(this, 11, sample_aspect_ratio);
		return this;
	}
	/** C type : AVDictionary* */
	@Field(12) 
	public Pointer<AVDictionary > metadata() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : AVDictionary* */
	@Field(12) 
	public AVStream metadata(Pointer<AVDictionary > metadata) {
		this.io.setPointerField(this, 12, metadata);
		return this;
	}
	/** C type : AVRational */
	@Field(13) 
	public AVRational avg_frame_rate() {
		return this.io.getNativeObjectField(this, 13);
	}
	/** C type : AVRational */
	@Field(13) 
	public AVStream avg_frame_rate(AVRational avg_frame_rate) {
		this.io.setNativeObjectField(this, 13, avg_frame_rate);
		return this;
	}
	/** C type : AVPacket */
	@Field(14) 
	public AVPacket attached_pic() {
		return this.io.getNativeObjectField(this, 14);
	}
	/** C type : AVPacket */
	@Field(14) 
	public AVStream attached_pic(AVPacket attached_pic) {
		this.io.setNativeObjectField(this, 14, attached_pic);
		return this;
	}
	/** C type : AVPacketSideData* */
	@Field(15) 
	public Pointer<AVPacketSideData > side_data() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : AVPacketSideData* */
	@Field(15) 
	public AVStream side_data(Pointer<AVPacketSideData > side_data) {
		this.io.setPointerField(this, 15, side_data);
		return this;
	}
	@Field(16) 
	public int nb_side_data() {
		return this.io.getIntField(this, 16);
	}
	@Field(16) 
	public AVStream nb_side_data(int nb_side_data) {
		this.io.setIntField(this, 16, nb_side_data);
		return this;
	}
	@Field(17) 
	public int event_flags() {
		return this.io.getIntField(this, 17);
	}
	@Field(17) 
	public AVStream event_flags(int event_flags) {
		this.io.setIntField(this, 17, event_flags);
		return this;
	}
	/** C type : info_struct* */
	@Field(18) 
	public Pointer<info_struct > info() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : info_struct* */
	@Field(18) 
	public AVStream info(Pointer<info_struct > info) {
		this.io.setPointerField(this, 18, info);
		return this;
	}
	/** < number of bits in pts (used for wrapping control) */
	@Field(19) 
	public int pts_wrap_bits() {
		return this.io.getIntField(this, 19);
	}
	/** < number of bits in pts (used for wrapping control) */
	@Field(19) 
	public AVStream pts_wrap_bits(int pts_wrap_bits) {
		this.io.setIntField(this, 19, pts_wrap_bits);
		return this;
	}
	@Field(20) 
	public long first_dts() {
		return this.io.getLongField(this, 20);
	}
	@Field(20) 
	public AVStream first_dts(long first_dts) {
		this.io.setLongField(this, 20, first_dts);
		return this;
	}
	@Field(21) 
	public long cur_dts() {
		return this.io.getLongField(this, 21);
	}
	@Field(21) 
	public AVStream cur_dts(long cur_dts) {
		this.io.setLongField(this, 21, cur_dts);
		return this;
	}
	@Field(22) 
	public long last_IP_pts() {
		return this.io.getLongField(this, 22);
	}
	@Field(22) 
	public AVStream last_IP_pts(long last_IP_pts) {
		this.io.setLongField(this, 22, last_IP_pts);
		return this;
	}
	@Field(23) 
	public int last_IP_duration() {
		return this.io.getIntField(this, 23);
	}
	@Field(23) 
	public AVStream last_IP_duration(int last_IP_duration) {
		this.io.setIntField(this, 23, last_IP_duration);
		return this;
	}
	@Field(24) 
	public int probe_packets() {
		return this.io.getIntField(this, 24);
	}
	@Field(24) 
	public AVStream probe_packets(int probe_packets) {
		this.io.setIntField(this, 24, probe_packets);
		return this;
	}
	@Field(25) 
	public int codec_info_nb_frames() {
		return this.io.getIntField(this, 25);
	}
	@Field(25) 
	public AVStream codec_info_nb_frames(int codec_info_nb_frames) {
		this.io.setIntField(this, 25, codec_info_nb_frames);
		return this;
	}
	/** C type : AVStreamParseType */
	@Field(26) 
	public IntValuedEnum<AVStreamParseType > need_parsing() {
		return this.io.getEnumField(this, 26);
	}
	/** C type : AVStreamParseType */
	@Field(26) 
	public AVStream need_parsing(IntValuedEnum<AVStreamParseType > need_parsing) {
		this.io.setEnumField(this, 26, need_parsing);
		return this;
	}
	/** C type : AVCodecParserContext* */
	@Field(27) 
	public Pointer<AVCodecParserContext > parser() {
		return this.io.getPointerField(this, 27);
	}
	/** C type : AVCodecParserContext* */
	@Field(27) 
	public AVStream parser(Pointer<AVCodecParserContext > parser) {
		this.io.setPointerField(this, 27, parser);
		return this;
	}
	/** C type : AVPacketList* */
	@Field(28) 
	public Pointer<AVPacketList > last_in_packet_buffer() {
		return this.io.getPointerField(this, 28);
	}
	/** C type : AVPacketList* */
	@Field(28) 
	public AVStream last_in_packet_buffer(Pointer<AVPacketList > last_in_packet_buffer) {
		this.io.setPointerField(this, 28, last_in_packet_buffer);
		return this;
	}
	/** C type : AVProbeData */
	@Field(29) 
	public AVProbeData probe_data() {
		return this.io.getNativeObjectField(this, 29);
	}
	/** C type : AVProbeData */
	@Field(29) 
	public AVStream probe_data(AVProbeData probe_data) {
		this.io.setNativeObjectField(this, 29, probe_data);
		return this;
	}
	/** C type : int64_t[16 + 1] */
	@Array({16 + 1}) 
	@Field(30) 
	public Pointer<Long > pts_buffer() {
		return this.io.getPointerField(this, 30);
	}
	/**
	 * < Only used if the format does not<br>
	 * support seeking natively.<br>
	 * C type : AVIndexEntry*
	 */
	@Field(31) 
	public Pointer<AVIndexEntry > index_entries() {
		return this.io.getPointerField(this, 31);
	}
	/**
	 * < Only used if the format does not<br>
	 * support seeking natively.<br>
	 * C type : AVIndexEntry*
	 */
	@Field(31) 
	public AVStream index_entries(Pointer<AVIndexEntry > index_entries) {
		this.io.setPointerField(this, 31, index_entries);
		return this;
	}
	@Field(32) 
	public int nb_index_entries() {
		return this.io.getIntField(this, 32);
	}
	@Field(32) 
	public AVStream nb_index_entries(int nb_index_entries) {
		this.io.setIntField(this, 32, nb_index_entries);
		return this;
	}
	@Field(33) 
	public int index_entries_allocated_size() {
		return this.io.getIntField(this, 33);
	}
	@Field(33) 
	public AVStream index_entries_allocated_size(int index_entries_allocated_size) {
		this.io.setIntField(this, 33, index_entries_allocated_size);
		return this;
	}
	/** C type : AVRational */
	@Field(34) 
	public AVRational r_frame_rate() {
		return this.io.getNativeObjectField(this, 34);
	}
	/** C type : AVRational */
	@Field(34) 
	public AVStream r_frame_rate(AVRational r_frame_rate) {
		this.io.setNativeObjectField(this, 34, r_frame_rate);
		return this;
	}
	@Field(35) 
	public int stream_identifier() {
		return this.io.getIntField(this, 35);
	}
	@Field(35) 
	public AVStream stream_identifier(int stream_identifier) {
		this.io.setIntField(this, 35, stream_identifier);
		return this;
	}
	@Field(36) 
	public long interleaver_chunk_size() {
		return this.io.getLongField(this, 36);
	}
	@Field(36) 
	public AVStream interleaver_chunk_size(long interleaver_chunk_size) {
		this.io.setLongField(this, 36, interleaver_chunk_size);
		return this;
	}
	@Field(37) 
	public long interleaver_chunk_duration() {
		return this.io.getLongField(this, 37);
	}
	@Field(37) 
	public AVStream interleaver_chunk_duration(long interleaver_chunk_duration) {
		this.io.setLongField(this, 37, interleaver_chunk_duration);
		return this;
	}
	@Field(38) 
	public int request_probe() {
		return this.io.getIntField(this, 38);
	}
	@Field(38) 
	public AVStream request_probe(int request_probe) {
		this.io.setIntField(this, 38, request_probe);
		return this;
	}
	@Field(39) 
	public int skip_to_keyframe() {
		return this.io.getIntField(this, 39);
	}
	@Field(39) 
	public AVStream skip_to_keyframe(int skip_to_keyframe) {
		this.io.setIntField(this, 39, skip_to_keyframe);
		return this;
	}
	@Field(40) 
	public int skip_samples() {
		return this.io.getIntField(this, 40);
	}
	@Field(40) 
	public AVStream skip_samples(int skip_samples) {
		this.io.setIntField(this, 40, skip_samples);
		return this;
	}
	@Field(41) 
	public long start_skip_samples() {
		return this.io.getLongField(this, 41);
	}
	@Field(41) 
	public AVStream start_skip_samples(long start_skip_samples) {
		this.io.setLongField(this, 41, start_skip_samples);
		return this;
	}
	@Field(42) 
	public long first_discard_sample() {
		return this.io.getLongField(this, 42);
	}
	@Field(42) 
	public AVStream first_discard_sample(long first_discard_sample) {
		this.io.setLongField(this, 42, first_discard_sample);
		return this;
	}
	@Field(43) 
	public long last_discard_sample() {
		return this.io.getLongField(this, 43);
	}
	@Field(43) 
	public AVStream last_discard_sample(long last_discard_sample) {
		this.io.setLongField(this, 43, last_discard_sample);
		return this;
	}
	@Field(44) 
	public int nb_decoded_frames() {
		return this.io.getIntField(this, 44);
	}
	@Field(44) 
	public AVStream nb_decoded_frames(int nb_decoded_frames) {
		this.io.setIntField(this, 44, nb_decoded_frames);
		return this;
	}
	@Field(45) 
	public long mux_ts_offset() {
		return this.io.getLongField(this, 45);
	}
	@Field(45) 
	public AVStream mux_ts_offset(long mux_ts_offset) {
		this.io.setLongField(this, 45, mux_ts_offset);
		return this;
	}
	@Field(46) 
	public long pts_wrap_reference() {
		return this.io.getLongField(this, 46);
	}
	@Field(46) 
	public AVStream pts_wrap_reference(long pts_wrap_reference) {
		this.io.setLongField(this, 46, pts_wrap_reference);
		return this;
	}
	@Field(47) 
	public int pts_wrap_behavior() {
		return this.io.getIntField(this, 47);
	}
	@Field(47) 
	public AVStream pts_wrap_behavior(int pts_wrap_behavior) {
		this.io.setIntField(this, 47, pts_wrap_behavior);
		return this;
	}
	@Field(48) 
	public int update_initial_durations_done() {
		return this.io.getIntField(this, 48);
	}
	@Field(48) 
	public AVStream update_initial_durations_done(int update_initial_durations_done) {
		this.io.setIntField(this, 48, update_initial_durations_done);
		return this;
	}
	/** C type : int64_t[16 + 1] */
	@Array({16 + 1}) 
	@Field(49) 
	public Pointer<Long > pts_reorder_error() {
		return this.io.getPointerField(this, 49);
	}
	/** C type : uint8_t[16 + 1] */
	@Array({16 + 1}) 
	@Field(50) 
	public Pointer<Byte > pts_reorder_error_count() {
		return this.io.getPointerField(this, 50);
	}
	@Field(51) 
	public long last_dts_for_order_check() {
		return this.io.getLongField(this, 51);
	}
	@Field(51) 
	public AVStream last_dts_for_order_check(long last_dts_for_order_check) {
		this.io.setLongField(this, 51, last_dts_for_order_check);
		return this;
	}
	@Field(52) 
	public byte dts_ordered() {
		return this.io.getByteField(this, 52);
	}
	@Field(52) 
	public AVStream dts_ordered(byte dts_ordered) {
		this.io.setByteField(this, 52, dts_ordered);
		return this;
	}
	@Field(53) 
	public byte dts_misordered() {
		return this.io.getByteField(this, 53);
	}
	@Field(53) 
	public AVStream dts_misordered(byte dts_misordered) {
		this.io.setByteField(this, 53, dts_misordered);
		return this;
	}
	@Field(54) 
	public int inject_global_side_data() {
		return this.io.getIntField(this, 54);
	}
	@Field(54) 
	public AVStream inject_global_side_data(int inject_global_side_data) {
		this.io.setIntField(this, 54, inject_global_side_data);
		return this;
	}
	/** C type : char* */
	@Field(55) 
	public Pointer<Byte > recommended_encoder_configuration() {
		return this.io.getPointerField(this, 55);
	}
	/** C type : char* */
	@Field(55) 
	public AVStream recommended_encoder_configuration(Pointer<Byte > recommended_encoder_configuration) {
		this.io.setPointerField(this, 55, recommended_encoder_configuration);
		return this;
	}
	/** C type : AVRational */
	@Field(56) 
	public AVRational display_aspect_ratio() {
		return this.io.getNativeObjectField(this, 56);
	}
	/** C type : AVRational */
	@Field(56) 
	public AVStream display_aspect_ratio(AVRational display_aspect_ratio) {
		this.io.setNativeObjectField(this, 56, display_aspect_ratio);
		return this;
	}
	/** C type : FFFrac* */
	@Field(57) 
	public Pointer<FFFrac > priv_pts() {
		return this.io.getPointerField(this, 57);
	}
	/** C type : FFFrac* */
	@Field(57) 
	public AVStream priv_pts(Pointer<FFFrac > priv_pts) {
		this.io.setPointerField(this, 57, priv_pts);
		return this;
	}
	/** C type : AVStreamInternal* */
	@Field(58) 
	public Pointer<AVStreamInternal > internal() {
		return this.io.getPointerField(this, 58);
	}
	/** C type : AVStreamInternal* */
	@Field(58) 
	public AVStream internal(Pointer<AVStreamInternal > internal) {
		this.io.setPointerField(this, 58, internal);
		return this;
	}
	/** C type : AVCodecParameters* */
	@Field(59) 
	public Pointer<AVCodecParameters > codecpar() {
		return this.io.getPointerField(this, 59);
	}
	/** C type : AVCodecParameters* */
	@Field(59) 
	public AVStream codecpar(Pointer<AVCodecParameters > codecpar) {
		this.io.setPointerField(this, 59, codecpar);
		return this;
	}
	/** <i>native declaration : libavformat\avformat.h:268</i> */
	public static class info_struct extends StructObject {
		static {
			BridJ.register();
		}
		@Field(0) 
		public long last_dts() {
			return this.io.getLongField(this, 0);
		}
		@Field(0) 
		public info_struct last_dts(long last_dts) {
			this.io.setLongField(this, 0, last_dts);
			return this;
		}
		@Field(1) 
		public long duration_gcd() {
			return this.io.getLongField(this, 1);
		}
		@Field(1) 
		public info_struct duration_gcd(long duration_gcd) {
			this.io.setLongField(this, 1, duration_gcd);
			return this;
		}
		@Field(2) 
		public int duration_count() {
			return this.io.getIntField(this, 2);
		}
		@Field(2) 
		public info_struct duration_count(int duration_count) {
			this.io.setIntField(this, 2, duration_count);
			return this;
		}
		@Field(3) 
		public long rfps_duration_sum() {
			return this.io.getLongField(this, 3);
		}
		@Field(3) 
		public info_struct rfps_duration_sum(long rfps_duration_sum) {
			this.io.setLongField(this, 3, rfps_duration_sum);
			return this;
		}
		/** C type : double[2][(30 * 12 + 30 + 3 + 6)]* */
		@Field(4) 
		public Pointer<Pointer<Double > > duration_error() {
			return this.io.getPointerField(this, 4);
		}
		/** C type : double[2][(30 * 12 + 30 + 3 + 6)]* */
		@Field(4) 
		public info_struct duration_error(Pointer<Pointer<Double > > duration_error) {
			this.io.setPointerField(this, 4, duration_error);
			return this;
		}
		@Field(5) 
		public long codec_info_duration() {
			return this.io.getLongField(this, 5);
		}
		@Field(5) 
		public info_struct codec_info_duration(long codec_info_duration) {
			this.io.setLongField(this, 5, codec_info_duration);
			return this;
		}
		@Field(6) 
		public long codec_info_duration_fields() {
			return this.io.getLongField(this, 6);
		}
		@Field(6) 
		public info_struct codec_info_duration_fields(long codec_info_duration_fields) {
			this.io.setLongField(this, 6, codec_info_duration_fields);
			return this;
		}
		@Field(7) 
		public int found_decoder() {
			return this.io.getIntField(this, 7);
		}
		@Field(7) 
		public info_struct found_decoder(int found_decoder) {
			this.io.setIntField(this, 7, found_decoder);
			return this;
		}
		@Field(8) 
		public long last_duration() {
			return this.io.getLongField(this, 8);
		}
		@Field(8) 
		public info_struct last_duration(long last_duration) {
			this.io.setLongField(this, 8, last_duration);
			return this;
		}
		@Field(9) 
		public long fps_first_dts() {
			return this.io.getLongField(this, 9);
		}
		@Field(9) 
		public info_struct fps_first_dts(long fps_first_dts) {
			this.io.setLongField(this, 9, fps_first_dts);
			return this;
		}
		@Field(10) 
		public int fps_first_dts_idx() {
			return this.io.getIntField(this, 10);
		}
		@Field(10) 
		public info_struct fps_first_dts_idx(int fps_first_dts_idx) {
			this.io.setIntField(this, 10, fps_first_dts_idx);
			return this;
		}
		@Field(11) 
		public long fps_last_dts() {
			return this.io.getLongField(this, 11);
		}
		@Field(11) 
		public info_struct fps_last_dts(long fps_last_dts) {
			this.io.setLongField(this, 11, fps_last_dts);
			return this;
		}
		@Field(12) 
		public int fps_last_dts_idx() {
			return this.io.getIntField(this, 12);
		}
		@Field(12) 
		public info_struct fps_last_dts_idx(int fps_last_dts_idx) {
			this.io.setIntField(this, 12, fps_last_dts_idx);
			return this;
		}
		public info_struct() {
			super();
		}
		public info_struct(Pointer pointer) {
			super(pointer);
		}
	};
	public AVStream() {
		super();
	}
	public AVStream(Pointer pointer) {
		super(pointer);
	}
}
